[project]
name = "cmap_trip-based_model"
version = "26.4.22"
requires-python = "==3.11.6"
dependencies = [
  "jinja2",
  "markdown",
  "myst-parser",
  "numpy~=1.0",
  "numexpr>=2.8.0,<2.8.5",
  "openpyxl",
  "pandas~=2.0",
  "pyarrow",
  "pyyaml",
  "sphinx",
  "sphinx_rtd_theme",
  "tqdm",
  "ipython>=9.15.0",
]

[tool.uv]
package = false
