      SUBROUTINE DATA2
	IMPLICIT INTEGER (A-Z)
C***********************************************************************
C     SUBROUTINE DATA2 READS A FILE OF ENUMERATED HOUSEHHOLDS FROM THE 
C     TRIP GENERATION.  EACH RECORD IS A HOUSEHOLD IDENTIFIED BY THE 
C     HOSUEHOLD TYPE VARIABLE USED FOR MATCHING (THE CODE BASED ON 
C     ADULTS, WORKERS, CHILDREN, AGE OF HEAD OF HOUSEHOLD, AND VEHICLES
C     AVAILABLE TO THE HOUSEHOLD).  THIS FILE IS COMMA DELIMITED AS
C     FOLLOWS:  
C
C       FIELD 1:  TRIP GENERATION SUBZONE
C       FIELD 2;  ZONE
C       FIELD 3:  HOUSEHOLD (VEHICLE) TYPE
C
C     THE SECOND PART OF THE SUBROUTINE READS AND STORES A FILE BUILT
C     FROM THE CMAP TRAVEL TRACKER SURVEY.  IT IS ALSO A COMMA DELIMITED
C     FILE WITH ONE RECORD FOR HOUSEHOLD (VEHICLE) TYPE AS FOLLOWS:
C
C       FIELD 1:  HOUSEHOLD (VEHICLE) TYPE
C       FIELD 2:  NUMBER OF HOUSEHOLDS OF THIS TYPE IN SURVEY DAYS
C                 (ONLY HOUSEHOLDS WITH WEEKDAY AUTO TRIPS ARE INCLUDED
C                  AND EACH WEEKDAY A HOUSEHOLD IS SURVEYED IS COUNTED,
C                  SO ONE HOUSEHOLD SURVEYED TWO WEEKDAYS EQUALS TWO
C                  HOUSEHOLDS IN FILE)
C       FIELD 3:  OBSERVED DRIVE ALONE HOME-WORK PERSON TRIPS
C       FIELD 4:  OBSERVED TWO PERSON AUTO HOME-WORK PERSON TRIPS
C       FIELD 5:  OBSERVED THREE OR MORE PERSON AUTO HOME-WORK PERSON
C                 TRIPS
C       FIELD 6:  OBSERVED DRIVE ALONE HOME-OTHER PERSON TRIPS
C       FIELD 7:  OBSERVED TWO PERSON AUTO HOME-OTHER PERSON TRIPS
C       FIELD 8:  OBSERVED THREE OR MORE PERSON AUTO HOME-OTHER PERSON
C                 TRIPS
C       FIELD 9:  OBSERVED DRIVE ALONE WORK-OTHER PERSON TRIPS
C       FIELD 10: OBSERVED TWO PERSON AUTO WORK-OTHER PERSON TRIPS
C       FIELD 11: OBSERVED THREE OR MORE PERSON AUTO WORK-OTHER PERSON
C                 TRIPS
C       FIELD 12: OBSERVED DRIVE ALONE OTHER-OTHER PERSON TRIPS
C       FIELD 13: OBSERVED TWO PERSON AUTO OTHER-OTHER PERSON TRIPS
C       FIELD 14: OBSERVED THREE OR MORE PERSON AUTO OTHER-OTHER PERSON
C                 TRIPS
C***********************************************************************
	INCLUDE 'COMMON_PARAMS.FI'
	INCLUDE 'COMMON_OCC.FI'

C# ##      CHARACTER*9 DAY
C# ##	CHARACTER*8 HOUR
      CHARACTER*10  CTIME10
      CHARACTER*2 DATE2(4), CTIME2(5)
      EQUIVALENCE (DATE8,DATE2(1)), (CTIME10,CTIME2(1))	
      CHARACTER*1 ASTERIX(80)/80*'*'/
      
      INTEGER*4 HH624(624)
C
C# ## Heither, 10-30-29: rename input file
C# ##      OPEN (UNIT=21,FILE='HI_HHENUM_IN.TXT',STATUS='OLD',ERR=9921)
      OPEN (UNIT=21,FILE='TG_HHENUM_OUTPUT.TXT',STATUS='OLD',ERR=9921)
      OPEN (UNIT=22,FILE='HH_VTYPE_TRIPS_IN.TXT',STATUS='OLD',ERR=9922)
C
      NEWZONE = 1
      TOTHH = 0
    5 CONTINUE   
      READ (21,*,END=9) SZ, ZONE, HHVTYPE

      Z_HHVTYPE(ZONE,HHVTYPE) = Z_HHVTYPE(ZONE,HHVTYPE) + 1
      TOTHH = TOTHH + 1
      
      IF (ZONE .NE. NEWZONE) THEN
        WRITE (*,'(A,I6)') ' HOUSEHOLDS READ FOR ZONE=', NEWZONE 
        NEWZONE = ZONE
      ENDIF    
      
      GO TO 5
    9 CONTINUE
      WRITE (*,'(A,I6)') ' HOUSEHOLDS READ FOR ZONE=', NEWZONE  
C
C     ACCUMULATE BY HHVTYPE
C
      DO HHT=1,624
        DO Z=1,ZONES
          HH624(HHT) = HH624(HHT) + Z_HHVTYPE(Z,HHT)
        ENDDO
      ENDDO  
           
      WRITE (16,'(/A)') ' TOTAL ENUMERATED HOUSEHOLDS'
      
      WRITE (16,'(/A)') '  HH_VTYPE   HOUSEHOLDS'
      WRITE (16,'(A)')  ' ----------------------'      
      
      DO HHT=1,624
        WRITE (16,'(I8,I13)') HHT, HH624(HHT)    
      ENDDO
      WRITE (16,'(A,I13)') '   TOTAL', TOTHH    
C
C     LOAD UP VEHICLE OCCUPANCY TRIPS FROM CMAP SURVEY
C
   15 CONTINUE
      READ (22,*,END=19) HHT, NUM_HH, HW1, HW2, HW3, HO1, HO2, HO3, WO1,
     A  WO2, WO3, OO1, OO2, OO3
     
      HI_HVTYPE(HHT) = NUM_HH
      HW_OCC1(HHT) = HW1
      HW_OCC2(HHT) = HW2
      HW_OCC3(HHT) = HW3
      HO_OCC1(HHT) = HO1
      HO_OCC2(HHT) = HO2
      HO_OCC3(HHT) = HO3
      WO_OCC1(HHT) = WO1
      WO_OCC2(HHT) = WO2
      WO_OCC3(HHT) = WO3
      OO_OCC1(HHT) = OO1
      OO_OCC2(HHT) = OO2
      OO_OCC3(HHT) = OO3 
      
      HW_TOT(HHT) = HW_OCC1(HHT) + HW_OCC2(HHT) + HW_OCC3(HHT)
      HO_TOT(HHT) = HO_OCC1(HHT) + HO_OCC2(HHT) + HO_OCC3(HHT)
      WO_TOT(HHT) = WO_OCC1(HHT) + WO_OCC2(HHT) + WO_OCC3(HHT)
      OO_TOT(HHT) = OO_OCC1(HHT) + OO_OCC2(HHT) + OO_OCC3(HHT)
      
      IF (HW_TOT(HHT) .GT. 0) THEN
        P_HW1(HHT) = HW_OCC1(HHT)/FLOAT(HW_TOT(HHT))
        P_HW2(HHT) = HW_OCC2(HHT)/FLOAT(HW_TOT(HHT))
        P_HW3(HHT) = HW_OCC3(HHT)/FLOAT(HW_TOT(HHT))
      ENDIF  
      
      IF (HO_TOT(HHT) .GT. 0) THEN
        P_HO1(HHT) = HO_OCC1(HHT)/FLOAT(HO_TOT(HHT))
        P_HO2(HHT) = HO_OCC2(HHT)/FLOAT(HO_TOT(HHT))
        P_HO3(HHT) = HO_OCC3(HHT)/FLOAT(HO_TOT(HHT))
      ENDIF   
      
      IF (WO_TOT(HHT) .GT. 0) THEN
        P_WO1(HHT) = WO_OCC1(HHT)/FLOAT(WO_TOT(HHT))
        P_WO2(HHT) = WO_OCC2(HHT)/FLOAT(WO_TOT(HHT))
        P_WO3(HHT) = WO_OCC3(HHT)/FLOAT(WO_TOT(HHT))
      ENDIF
      
      IF (OO_TOT(HHT) .GT. 0) THEN
        P_OO1(HHT) = OO_OCC1(HHT)/FLOAT(OO_TOT(HHT))
        P_OO2(HHT) = OO_OCC2(HHT)/FLOAT(OO_TOT(HHT))
        P_OO3(HHT) = OO_OCC3(HHT)/FLOAT(OO_TOT(HHT))
      ENDIF   
      
      GO TO 15
   19 CONTINUE
      
      WRITE (16,'(/A)') ' TRIPS BY HOUSEHOLD TYPE (VEHICLE)'
      WRITE (16,'(/A)') '                                               
     A      AUTO TRIPS BY OCCUPANCY'
      WRITE (16,'(/A)') '                         HOME-WORK             
     A HOME-OTHER              WORK-OTHER              OTHER-OTHER '
      WRITE (16,'( A)') '                  ----------------------  -----
     A-----------------  ----------------------  ----------------------'
      WRITE (16,'( A)') '  HH_VTYPE   HHS   1 PER   2 PER  3+ PER   1 PE
     AR   2 PER  3+ PER   1 PER   2 PER  3+ PER   1 PER   2 PER  3+ PER'
      WRITE (16,'( A)') ' ----------------------------------------------
     A-----------------------------------------------------------------'

      DO HHT=1,624
        WRITE (16,'(I10,I6,12I8)') HHT, HI_HVTYPE(HHT), HW_OCC1(HHT), 
     A    HW_OCC2(HHT), HW_OCC3(HHT), HO_OCC1(HHT), HO_OCC2(HHT), 
     B    HO_OCC3(HHT), WO_OCC1(HHT), WO_OCC2(HHT), WO_OCC3(HHT),
     C    OO_OCC1(HHT), OO_OCC2(HHT), OO_OCC3(HHT)
      ENDDO  
C
C     THIS CALCULATION ESTIMATES THE NUMBER OF TRIPS BY HOUSEHOLD
C     TYPE IN A ZONE
C
      DO Z=1,ZONES
        DO HHT=1,624
          IF (HI_HVTYPE(HHT) .GT. 0) THEN  
            HW_TRIPS(Z,HHT) = 
     A        (Z_HHVTYPE(Z,HHT)/FLOAT(HI_HVTYPE(HHT)))*HW_TOT(HHT)
            HO_TRIPS(Z,HHT) = 
     A        (Z_HHVTYPE(Z,HHT)/FLOAT(HI_HVTYPE(HHT)))*HO_TOT(HHT)
            WO_TRIPS(Z,HHT) = 
     A        (Z_HHVTYPE(Z,HHT)/FLOAT(HI_HVTYPE(HHT)))*WO_TOT(HHT)
            OO_TRIPS(Z,HHT) = 
     A        (Z_HHVTYPE(Z,HHT)/FLOAT(HI_HVTYPE(HHT)))*OO_TOT(HHT)
          ELSE
            HW_TRIPS(Z,HHT) = 0
            HO_TRIPS(Z,HHT) = 0
            WO_TRIPS(Z,HHT) = 0
            OO_TRIPS(Z,HHT) = 0
          ENDIF  
        ENDDO
      ENDDO 
      
      
      DO Z=1,ZONES
        DO HHT =1,624
          HW_ZONE(Z) = HW_ZONE(Z) + HW_TRIPS(Z,HHT)  
          HO_ZONE(Z) = HO_ZONE(Z) + HO_TRIPS(Z,HHT)  
  
          HW_REG = HW_REG + HW_TRIPS(Z,HHT)
          HO_REG = HO_REG + HO_TRIPS(Z,HHT)
          WO_REG = WO_REG + WO_TRIPS(Z,HHT)
          OO_REG = OO_REG + OO_TRIPS(Z,HHT)
          
          HW_REG1 = HW_REG1 + HW_TRIPS(Z,HHT)*P_HW1(HHT)
          HW_REG2 = HW_REG2 + HW_TRIPS(Z,HHT)*P_HW2(HHT)
          HW_REG3 = HW_REG3 + HW_TRIPS(Z,HHT)*P_HW3(HHT)
      
          HO_REG1 = HO_REG1 + HO_TRIPS(Z,HHT)*P_HO1(HHT)
          HO_REG2 = HO_REG2 + HO_TRIPS(Z,HHT)*P_HO2(HHT)
          HO_REG3 = HO_REG3 + HO_TRIPS(Z,HHT)*P_HO3(HHT)

          WO_REG1 = WO_REG1 + WO_TRIPS(Z,HHT)*P_WO1(HHT)
          WO_REG2 = WO_REG2 + WO_TRIPS(Z,HHT)*P_WO2(HHT)
          WO_REG3 = WO_REG3 + WO_TRIPS(Z,HHT)*P_WO3(HHT)

          OO_REG1 = OO_REG1 + OO_TRIPS(Z,HHT)*P_OO1(HHT)
          OO_REG2 = OO_REG2 + OO_TRIPS(Z,HHT)*P_OO2(HHT)
          OO_REG3 = OO_REG3 + OO_TRIPS(Z,HHT)*P_OO3(HHT)
        ENDDO
      ENDDO
C      
      P_REG_HW1 = HW_REG1/HW_REG
      P_REG_HW2 = HW_REG2/HW_REG
      P_REG_HW3 = HW_REG3/HW_REG
      P_REG_HO1 = HO_REG1/HO_REG
      P_REG_HO2 = HO_REG2/HO_REG
      P_REG_HO3 = HO_REG3/HO_REG
      P_REG_WO1 = WO_REG1/WO_REG
      P_REG_WO2 = WO_REG2/WO_REG
      P_REG_WO3 = WO_REG3/WO_REG
      P_REG_OO1 = OO_REG1/OO_REG
      P_REG_OO2 = OO_REG2/OO_REG
      P_REG_OO3 = OO_REG3/OO_REG 
      
      WRITE (16,'(/A)') ' REGIONAL DEFAULT VALUES USED FOR SURVEY HOUSEH
     AOLD MODE CHOICE MISMATCH'
      
      WRITE (16,'(/A)')    ' HOME-WORK TRIPS'
      WRITE (16,'(A,F10.1)')  '   TOTAL=',HW_REG
      WRITE (16,'(A,F10.1,A,F6.3)') '   DRIVE ALONE=',HW_REG1,
     A' PROB=',P_REG_HW1
      WRITE (16,'(A,F10.1,A,F6.3)') '   TWO PERSON=',HW_REG2,
     A' PROB=',P_REG_HW2 
      WRITE (16,'(A,F10.1,A,F6.3)') '   THREE OR MORE PERSON=',HW_REG3,
     A' PROB=',P_REG_HW3

      WRITE (16,'(/A)')    ' HOME-OTHER TRIPS'
      WRITE (16,'(A,F10.1)')  '   TOTAL=',HO_REG
      WRITE (16,'(A,F10.1,A,F6.3)') '   DRIVE ALONE=',HO_REG1,
     A' PROB=',P_REG_HO1
      WRITE (16,'(A,F10.1,A,F6.3)') '   TWO PERSON=',HO_REG2,
     A' PROB=',P_REG_HO2 
      WRITE (16,'(A,F10.1,A,F6.3)') '   THREE OR MORE PERSON=',HO_REG3,
     A' PROB=',P_REG_HO3

      WRITE (16,'(/A)')    ' WORK-OTHER TRIPS'
      WRITE (16,'(A,F10.1)')  '   TOTAL=',WO_REG
      WRITE (16,'(A,F10.1,A,F6.3)') '   DRIVE ALONE=',WO_REG1,
     A' PROB=',P_REG_WO1
      WRITE (16,'(A,F10.1,A,F6.3)') '   TWO PERSON=',WO_REG2,
     A' PROB=',P_REG_WO2 
      WRITE (16,'(A,F10.1,A,F6.3)') '   THREE OR MORE PERSON=',WO_REG3,
     A' PROB=',P_REG_WO3

      WRITE (16,'(/A)')    ' OTHER-OTHER TRIPS'
      WRITE (16,'(A,F10.1)')  '   TOTAL=',OO_REG
      WRITE (16,'(A,F10.1,A,F6.3)') '   DRIVE ALONE=',OO_REG1,
     A' PROB=',P_REG_OO1
      WRITE (16,'(A,F10.1,A,F6.3)') '   TWO PERSON=',OO_REG2,
     A' PROB=',P_REG_OO2 
      WRITE (16,'(A,F10.1,A,F6.3)') '   THREE OR MORE PERSON=',OO_REG3,
     A' PROB=',P_REG_OO3
      
      CLOSE (21)
      CLOSE (22)
      
      RETURN

 9921 WRITE (31,'(/A)') ' ERROR DETECTED WHILE READING TG_HHENUM_OUTPUT 
     A.TXT FILE'
	STOP 9921
 9922 WRITE (31,'(/A)') ' ERROR DETECTED WHILE READING HH_VTYPE_TRIPS_IN
     A.TXT FILE'
	STOP 9922   
C
      END