#Program creates the scenario-specific DISTR and M01 files used by Pre-Distribution and Mode Choice based on Eash's methodology.
#Code adapted by Karly Cazzato, 3/23/2023, from previous SAS script by Craig Heither

#Script conversion notes####
#"Regular CMAP Zones" refers to zones <= 2977 
#"Out Zones" refers to zones > 2977
#Observations generated by R code may have a "-1" difference from SAS code data
  #SAS rounds values 0.5 up; R rounds values 0.5 down
    #ex: 6.5 SAS = 7; R = 6
#SAS script has comments that PNR distance cap removed for regular CMAP zones but in the code it wasn't. Cap retained here

#File information####
#zone system 17

#M01 file components
  #Socioeconomic data
  #Workers per vehicle at destination (from CTPP) from m01auto.csv
  #Zone type flag from m01type.csv
  #Zonal attributes based on the Emme network:
    #Park-&-Ride cost (cents) - based on lot closest to Zone centroid (within 10 miles)
    #Park-&-Ride flag
    #First wait for bus work trip (minutes)
    #First wait for bus non-work trip (minutes)
    #First wait for feeder bus work trip (minutes)
    #First wait for feeder bus non-work trip (minutes)

#DISTR file components
#All zonal attributes calculated using Emme network data
#Emme vehicle types: 25-27=mode B, 31-33=mode E, 28=mode P, 29=mode Q, 30=mode L, 1-5=mode C, 6-24=mode M
#metra, cta rail, & park-&-ride (Fields are consistent and calculated separately for mode category)
  #Additional impedance for zones >= 2977: outside CMAP 7 counties and only contain one subzone; use random points shape file to calculate distance (sz17_centroids.dbf)
  #Mean distance to station (miles) weighted by subzone households (HH_IN.TXT)
    #The distance (Euclidean) of the closest rail station to each subzone centroid is determined
    #The subzone distances are averaged to determine zonal mean
    #No cap for distance
    #Impedance: use Manhattan distance instead
  #Standard deviation of distance to station 
    #Square root of the sum of (zonal variance + a subzone variance)
    #Subzone variance estimated by Eash to =0.042
  #Type of distribution (used by mode choice)
    # 101 = normal distribution; default
    # mode choice supports 102 = exponential distribution; for the current model all distributions will be set to 101
#bus and feeder bus (Fields are consistent and calculated separately for mode category)
  #buffer zones from 0.1 to 1.1 miles 
  #length of the buffer that touches any part of the zone, or 999 if no buffer intersects the zone
  #length of the smallest buffer that covers the entire zone, or 1.1 if none exist and minimum does not equal 999
  #total area of the zone covered by the minimum buffer / total area of the zone covered by the maximum buffer, or 999 if no minimum/max exist
  #Zones that have Pace stops but no CTA bus stops have an additional impedance based on sidewalk density

#0. set up####
loadPackage <- function (package) {
  if(!package %in% .packages(all = TRUE)) {
    install.packages(package, repos = "http://cran.r-project.org")
  }
  eval(parse(text=paste("library(", package, ")", sep="")))
}

loadPackage("sf") #for spatial analysis
loadPackage("tidyverse") #for data manipulation and viewing
loadPackage("foreign") #for loading dbfs

#1. Create variables####
#DISTR variables
eash <- 0.042 #Eash's estimate for subzone variance
rlvar <- 101 #default value for DISTR rail variance
subznZn <- 2977 #highest zone number containing multiple subzones

#Time period lengths in minutes
ammin <- 180 #6am-9am
mdmin <- 420 #9am-4pm

#2. Input files####
in1 <- read.table("temp/node.txt", header=TRUE) #transit stop node coordinates morning
in1M <- read.table("temp/node_midday.txt", header = TRUE) #transit stop node coordinates midday

in2 <- read.table("temp/transit.itin", header = TRUE) #transit itinerary morning
in2M <- read.table("temp/transit_midday.itin", header = TRUE) #transit itinerary midday 

in5 <- read.table("../tg/data/m01tg.txt") #income data
in6 <-  read.csv("../tg/data/m01auto.csv") #auto occupancy data
in7 <- read.csv("../tg/data/m01type.csv") #type data
in8 <- read.table("../tg/fortran/HH_IN.txt", sep = ',') #HH weight 

in9 <- read.dbf("../data/distr/zone_random_points.dbf") #random points for impedance
szC<- read.dbf("../data/distr/sz17_centroids.dbf") #subzone coordinates
znC <- read.dbf("../data/distr/zncntrd.dbf") #need to add into the data folder
zones <- read_sf(dsn = "../data/distr/zone17.shp", layer = "zone17") #zone area and geometry


#3. Prepare node and transit files for distance analysis####
#format node cost and location files 
stops <- in1 %>%
  select(-result) %>%
  rename(node = inode, pspac = X.pspac, pcost = X.pcost, xcoord = xi, ycoord = yi, zone = X.zone) %>%
  group_by(node)
stops_mdy <- in1M %>%
  select(-result) %>%
  rename(node = inode, pspac = X.pspac, pcost = X.pcost, xcoord = xi, ycoord = yi, zone = X.zone) %>%
  group_by(node)

#format itinerary data
itin <- in2 %>%
  select(-result) %>%
  rename(anode = inode, node = jnode, dwtime = dwt) %>%
  mutate(ord = 1:nrow(in2)) %>% 
  group_by(line) %>%
  arrange(ord) %>%
  slice(1L, row_number()) %>%
  mutate(node = case_when(row_number() == 1 ~ anode, row_number() != 1 ~ node),
         dwtime = case_when(row_number() == 1 ~ 0.01, row_number() != 1 ~ dwtime)) %>%
  filter(dwtime >0) %>% 
  select(-anode) %>%
  group_by(node) %>%
  left_join(stops, by = "node")

itin_mdy <- in2M %>%
  select(-result) %>%
  rename(anode = inode, node = jnode, dwtime = dwt) %>%
  mutate(ord_mdy = 1:nrow(in2M)) %>% 
  group_by(line) %>%
  arrange(ord_mdy) %>%
  slice(1L, row_number()) %>%
  mutate(node = case_when(row_number() == 1 ~ anode, row_number() != 1 ~ node),
         dwtime = case_when(row_number() == 1 ~ 0.01, row_number() != 1 ~ dwtime)) %>%
  filter(dwtime >0) %>%
  select(-anode) %>%
  group_by(node) %>%
  left_join(stops_mdy, by = "node") %>% 
  rename(hdwy_mdy = hdwy, 
         xcoord_mdy = xcoord, 
         ycoord_mdy = ycoord, 
         dwtime_mdy = dwtime, 
         veh_mdy = veh, 
         pspac_mdy = pspac, 
         pcost_mdy = pcost)

#4. Create separate stop files by mode####
#4a.  create metra station data frame
metra <- itin %>%
  filter(node < 49000, veh >=6, veh <= 24) %>%
  select(node, xcoord, ycoord, veh) %>%
  group_by(node)
metra <- metra[!duplicated(metra$node), ]

#4b. create CTA rail station data frame
ctaRail <- itin %>%
  filter(node < 39000, veh >= 1, veh <= 5) %>%
  select(node, xcoord, ycoord) %>%
  group_by(node)
ctaRail <- ctaRail[!duplicated(ctaRail), ]

#4c. create regular bus stop data frame
#i. am time
bus <- itin %>%
  filter(veh >= 25, veh != 30) 
bus <- bus[!duplicated(bus), ]
bus$frequent <- ammin/bus$hdwy

regbus_am <- bus %>%
  group_by(node) %>%
  summarise(hdwy = weighted.mean(hdwy, frequent), xcoord = max(xcoord), ycoord = max(ycoord), zone = max(zone)) %>%
  mutate(hdwy = round(hdwy))
  
#ii. mid-day time
bus_mdy <- itin_mdy %>%
  filter(veh_mdy >= 25, veh_mdy != 30)
bus_mdy <- bus_mdy[!duplicated(bus_mdy), ]
bus_mdy$frequent <- mdmin/bus_mdy$hdwy_mdy

regbus_mdy <- bus_mdy %>%
  group_by(node) %>%
  summarise(hdwy_mdy = weighted.mean(hdwy_mdy, frequent), xcoord_mdy = max(xcoord_mdy), ycoord_mdy = max(ycoord_mdy), zone_mdy = max(zone)) %>%
  mutate(hdwy_mdy = round(hdwy_mdy))

#iii. merge am and mday bus times
regbus <- merge(regbus_am, regbus_mdy, by = "node", all = T)

regbus <- regbus %>%
  mutate(xcoord = case_when(is.na(xcoord) ~ xcoord_mdy, !is.na(xcoord) ~ xcoord),
         ycoord = case_when(is.na(ycoord) ~ ycoord_mdy, !is.na(ycoord) ~ ycoord),
         hdwy = case_when(is.na(hdwy) ~ 888, !is.na(hdwy)~ hdwy), 
         hdwy_mdy = case_when(is.na(hdwy_mdy)~ 888, !is.na(hdwy_mdy)~ hdwy_mdy),
         zone = case_when(is.na(zone) ~ zone_mdy, !is.na(zone) ~ zone)) %>%
  select(-zone_mdy)

#4d. create feeder bus stop data frame
#i. am time
feed <- itin %>%
  filter(veh==30)
feed <- feed[!duplicated(feed), ]
feed$frequent <- ammin/feed$hdwy

fdbus_am <- feed %>%
  group_by(node) %>%
  summarise(hdwy = weighted.mean(hdwy, frequent), xcoord = max(xcoord), ycoord = max(ycoord), zone = max(zone)) %>%
  mutate(hdwy = round(hdwy))

#ii. mid-day time
feed_mdy <- itin_mdy %>%
  filter(veh_mdy==30)
feed_mdy <- feed_mdy[!duplicated(feed_mdy), ]
feed_mdy$frequent <- mdmin/feed_mdy$hdwy_mdy

fdbus_mdy <- feed_mdy %>%
  group_by(node) %>%
  summarise(hdwy_mdy = weighted.mean(hdwy_mdy, frequent), xcoord_mdy = max(xcoord_mdy), ycoord_mdy = max(ycoord_mdy), zone_mdy = max(zone)) %>%
  mutate(hdwy_mdy = round(hdwy_mdy))

#iii. merge am and mday bus times
fdbus <- merge(fdbus_am, fdbus_mdy, by = "node", all = T)

fdbus <- fdbus %>%
  mutate(xcoord = case_when(is.na(xcoord) ~ xcoord_mdy, !is.na(xcoord) ~ xcoord),
         ycoord = case_when(is.na(ycoord) ~ ycoord_mdy, !is.na(ycoord) ~ ycoord),
         hdwy = case_when(is.na(hdwy) ~ 888, !is.na(hdwy)~ hdwy), 
         hdwy_mdy = case_when(is.na(hdwy_mdy)~ 888, !is.na(hdwy_mdy)~ hdwy_mdy),
         zone = case_when(is.na(zone) ~ zone_mdy, !is.na(zone) ~ zone)) %>%
  select(-zone_mdy)

#4e. create park-n-ride data frame
pnr <- stops %>%
  filter(pspac > 0 | pcost > 0)
pnr <- pnr[!duplicated(pnr), ]

#5. Rail and Park-and-Ride: distance from each station to each subzone centroid####
#5a. link stations with subzone centroids
#impedance random points
in9 <- in9 %>% rename(zone  = zone17)

#format data
metra_sbzn <- metra %>%
  rename(xi = xcoord, yi = ycoord) %>%
  merge(szC, all = TRUE) %>%
  rename(zone = zone17)
cta_sbzn <- ctaRail %>%
  rename(xi = xcoord, yi = ycoord) %>%
  merge(szC, all = TRUE) %>%
  rename(zone = zone17)
pnr_sbzn <- pnr %>%
  rename(xi = xcoord, yi = ycoord) %>%
  select(-zone) %>%
  merge(szC, all = TRUE) %>%
  rename(zone = zone17)

#5b. distance for zones with subzone>1; select closest station to each subzone centroid
metra_cmap <- metra_sbzn %>%
  filter(zone <= subznZn) %>%
  mutate(dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  mutate(mdist = dist/5280)%>%
  group_by(subzone17) %>%
  slice(which.min(mdist))
cta_cmap <- cta_sbzn %>%
  filter(zone <= subznZn) %>%
  mutate(dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  mutate(mdist = dist/5280)%>%
  group_by(subzone17) %>%
  slice(which.min(mdist))
pnr_cmap <- pnr_sbzn %>%
  filter(zone <= subznZn) %>%
  mutate(dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  mutate(mdist = dist/5280, mdist = case_when(mdist <=19.95 ~ mdist, mdist > 19.95 ~ 19.95))%>%
  group_by(subzone17)%>%
  slice(which.min(mdist))

#5c. extra impedance on distance for zones with subzone=1 
metra_out <- metra_sbzn %>%
  filter(zone > subznZn) %>% 
  mutate(St_SZN_dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>% #closest station to each subzone centroid
  group_by(subzone17)%>%
  slice(which.min(St_SZN_dist))%>%
  left_join(in9, by = "zone", multiple = "all") %>%
  mutate(dist = (abs(POINT_X-xi)) + (abs(POINT_Y-yi)) ) %>% #use random points to generate distances for average
  mutate(mdist = dist/5280) %>%
  group_by(subzone17)
cta_out <- cta_sbzn %>%
  filter(zone > subznZn) %>% 
  mutate(St_SZN_dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  group_by(subzone17)%>%
  slice(which.min(St_SZN_dist))%>%
  left_join(in9, by = "zone", multiple = "all") %>%
  mutate(dist = (abs(POINT_X-xi)) + (abs(POINT_Y-yi)) ) %>%
  mutate(mdist = dist/5280) %>%
  group_by(subzone17)
pnr_out <- pnr_sbzn %>%
  filter(zone > subznZn) %>% 
  mutate(St_SZN_dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  group_by(subzone17)%>%
  slice(which.min(St_SZN_dist))%>%
  left_join(in9, by = "zone", multiple = "all") %>%
  mutate(dist = (abs(POINT_X-xi)) + (abs(POINT_Y-yi)) ) %>%
  mutate(mdist = dist/5280) %>%
  group_by(subzone17)

#6. Rail and Park-and-Ride: Mean and SD####
#6a. create household weight at zone and subzone level
hh_sbzn <- in8 %>%
  rename(subzone17 = V1, hhn = V2) %>%
  select(subzone17, hhn)
hh_sbzn['hhn'][hh_sbzn['hhn'] == 0] <- 1 

#6b. Rail and PNR: >1 subzone
metra_cmapsum <- metra_cmap %>%
  left_join(hh_sbzn, by = "subzone17") %>%
  group_by(zone) %>%
  summarise(meanDist_m = weighted.mean(mdist, hhn),
            sd_m = sqrt((var(mdist) + eash))) %>%
  mutate(distr_m = rlvar,
         meanDist_m = round(meanDist_m,2),
         sd_m = round(sd_m, 2))
metra_cmapsum['sd_m'][is.na(metra_cmapsum['sd_m'])] <- sqrt(eash)
cta_cmapsum <- cta_cmap %>%
  group_by(zone) %>%
  left_join(hh_sbzn, by = "subzone17") %>%
  summarise(meanDist_c = weighted.mean(mdist, hhn), 
            sd_c = sqrt((var(mdist) + eash))) %>%
  mutate(distr_c = rlvar,
         meanDist_c = round(meanDist_c,2),
         sd_c = round(sd_c, 2))
cta_cmapsum['sd_c'][is.na(cta_cmapsum['sd_c'])] <- sqrt(eash)
pnr_cmapsum <- pnr_cmap %>%
  group_by(zone) %>%
  left_join(hh_sbzn, by = "subzone17") %>%
  summarise(meanDist_p = weighted.mean(mdist, hhn), 
            sd_p = sqrt((var(mdist) + eash))) %>%
  mutate(distr_p = rlvar,
         meanDist_p = round(meanDist_p,2),
         sd_p = round(sd_p, 2))
pnr_cmapsum['sd_p'][is.na(pnr_cmapsum['sd_p'])] <- sqrt(eash)
pnr_cmapsum['sd_p'][pnr_cmapsum['meanDist_p'] == 19.95] <- sqrt(eash)


#6c. Rail and PNR: extra impedance for =1 subzone, no hh weight
metra_outsum <- metra_out %>%
  group_by(zone) %>%
  summarise(meanDist_m = mean(mdist), sd_m = sqrt(var(mdist))) %>%
  mutate(distr_m = rlvar,
         meanDist_m = round(meanDist_m,2),
         sd_m = round(sd_m, 2))
metra_outsum['sd_m'][is.na(metra_outsum['sd_m'])] <- sqrt(eash)
cta_outsum <- cta_out %>%
  group_by(zone) %>%
  summarise(meanDist_c = mean(mdist), sd_c = sqrt(var(mdist)))  %>%
  mutate(distr_c = rlvar,
         meanDist_c = round(meanDist_c,2),
         sd_c = round(sd_c, 2))
cta_outsum['sd_c'][is.na(cta_outsum['sd_c'])] <- sqrt(eash)
pnr_outsum <- pnr_out %>%
  group_by(zone)  %>%
  summarise(meanDist_p = mean(mdist), sd_p = sqrt(var(mdist)))  %>%
  mutate(distr_p = rlvar,
         meanDist_p = round(meanDist_p,2),
         sd_p = round(sd_p, 2))
pnr_outsum['sd_p'][is.na(pnr_outsum['sd_p'])] <- sqrt(eash)


#7. Bus and feeder bus: spatial buffers####
#add modification for sidewalk density
znsqmi <- zones %>% st_drop_geometry(NULL) %>% select(zone17, sqmi)
pace_s <- bus %>%
  filter(veh == 28 | veh == 29 | veh == 30)%>%
  group_by(zone) %>%
  summarize(pace = n()) %>%
  rename(zone17 = zone)

cta_s <- bus %>%
  filter(veh != 28 & veh != 29 & veh != 30) %>%
  group_by(zone) %>%
  summarize(cta = n()) %>%
  rename(zone17 = zone)

#pace flag cutoffs reflect the distribution of sidewalk density in the whole region
sidewalk_zn <- in8 %>%
  rename(subzone17 = V1, sidewalkD = V36) %>%
  select(subzone17, sidewalkD) %>%
  left_join(szC, by = "subzone17") %>%
  group_by(zone17) %>%
  left_join(znsqmi, by = "zone17") %>%
  summarize(sidewalkDW = weighted.mean(sidewalkD, sqmi)) %>%
  left_join(pace_s, by = "zone17")  %>%
  mutate(paceFlag = case_when(
    is.na(pace)  ~ 1,
    !is.na(pace) & sidewalkDW  >= 0 & sidewalkDW  <= 2 ~ .25,
    !is.na(pace) & sidewalkDW  > 2 & sidewalkDW  <= 11.47 ~ .5,
    !is.na(pace) & sidewalkDW  > 11.47 & sidewalkDW  <= 29.17 ~ .75,
    !is.na(pace) & sidewalkDW  > 29.17 ~ 1
  )) %>%
  left_join(cta_s, by = "zone17")
sidewalk_zn[is.na(sidewalk_zn)] <- 0
sidewalk_zn <- sidewalk_zn %>%   mutate(paceOnly = ifelse(pace > 0 & cta == 0, 1, 0))

#create shapefiles for analysis
temp_bus_Layer = st_as_sf(regbus, coords = c("xcoord", "ycoord"), crs = 26771) #crs = 26771 this is the projection to be used for all shape files
temp_feed_Layer = st_as_sf(fdbus, coords = c("xcoord", "ycoord"), crs = 26771)

#buffers (in feet) miles: (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 ,1.1)
dist = c(528, 1056, 1584, 2112, 2640, 3168, 3696, 4224, 4752, 5280 , 5808)
x = 1
for (d in dist){
  m = dist[x] 
  
  temp_bus_ring_shp = st_union(st_buffer(temp_bus_Layer, dist = m, endCapStyle = "ROUND")) #create buffers and unite buffers at distance level
  temp_bus_ring_shp <- temp_bus_ring_shp %>% st_union() 
  temp_bus_dislv_shp <- st_intersection(zones, temp_bus_ring_shp) #intersect buffers with zone system
  
  temp_feed_ring_shp = st_buffer(temp_feed_Layer, dist = m, endCapStyle = "ROUND") #repeat for feeder busses
  temp_feed_ring_shp <- temp_feed_ring_shp %>% st_union() 
  temp_feed_dislv_shp <- st_intersection(zones, temp_feed_ring_shp) 
  
  if (x == 1) {
    temp_bus_dislv_inter <- temp_bus_dislv_shp %>% mutate(area = as.numeric(st_area(.)))%>% st_drop_geometry(NULL) %>% mutate(distance = m) #remove goemetry to make data easier to work with
    
    temp_feed_dislv_inter <- temp_feed_dislv_shp %>% mutate(area = as.numeric(st_area(.)))%>% st_drop_geometry(NULL) %>% mutate(distance = m)
    
  }else {
    temp_bus <- temp_bus_dislv_shp %>% mutate(area = as.numeric(st_area(.))) %>% st_drop_geometry(NULL) %>% mutate(distance = m)
    
    temp_feed <- temp_feed_dislv_shp %>% mutate(area = as.numeric(st_area(.)))%>% st_drop_geometry(NULL) %>% mutate(distance = m)
    
    temp_bus_dislv_inter <- temp_bus_dislv_inter %>% rbind(temp_bus)
    temp_feed_dislv_inter <- temp_feed_dislv_inter %>% rbind(temp_feed)
  }
  
  x = x+1
  
}


bus_min <- temp_bus_dislv_inter %>%
  mutate(areaMi_Min = area/(5280^2), distance = distance/5280) %>%
  arrange(distance) %>%
  group_by(zone17) %>%
  filter(distance == min(distance))

bus_max <- temp_bus_dislv_inter %>%
  mutate(areaMi_Max = area/(5280^2), distance = distance/5280, prop = areaMi_Max/sqmi) %>%
  filter(prop >= 0.97) %>%
  arrange(distance) %>%
  group_by(zone17) %>%
  filter(distance == min(distance)) %>%
  right_join(bus_min, by = "zone17") %>%
  rename(max = distance.x, min = distance.y) %>%
  mutate(max = case_when(is.na(max) ~ 1.1, !is.na(max) ~ max), 
         prop = case_when(is.na(areaMi_Max) ~ areaMi_Min/((1.1^2)*pi), !is.na(areaMi_Max) ~ areaMi_Min/areaMi_Max)) %>%
  select(zone17, min, max, prop) %>%
  left_join(sidewalk_zn, by = "zone17") %>%
  mutate (prop2 = case_when(
    paceOnly == 1 ~ round(prop*paceFlag,2), #pace only flag adjustment 
    paceOnly != 1 ~ round(prop,2)
  )) %>%
  select(zone17, min, max, prop) %>%
  rename(minB = min, maxB = max, areaB = prop)
bus_max[is.na(bus_max)] <- 999

fbus_min <- temp_feed_dislv_inter %>%
  mutate(areaMi_Min = area/(5280^2), distance = distance/5280) %>%
  arrange(distance) %>%
  group_by(zone17) %>%
  filter(distance == min(distance))

fbus_max <- temp_feed_dislv_inter %>%
  mutate(areaMi_Max = area/(5280^2), distance = distance/5280, prop = areaMi_Max/sqmi) %>%
  filter(prop >= 0.97) %>%
  arrange(distance) %>%
  group_by(zone17) %>%
  filter(distance == min(distance)) %>%
  right_join(fbus_min, by = "zone17") %>%
  rename(max = distance.x, min = distance.y) %>%
  mutate(max = case_when(is.na(max) ~ 1.1, !is.na(max) ~ max), 
         prop = case_when(is.na(areaMi_Max) ~ areaMi_Min/((1.1^2)*pi), !is.na(areaMi_Max) ~ areaMi_Min/areaMi_Max)) %>%
  select(zone17, min, max, prop) %>%
  right_join(sidewalk_zn, by = "zone17") %>%
  mutate (prop = case_when(
    paceOnly == 1 ~ round(prop*paceFlag,2),
    paceOnly != 1 ~ round(prop,2)
  )) %>%
  select(zone17, min, max, prop) %>%
  rename(minF = min, maxF = max, areaF = prop) 
fbus_max[is.na(fbus_max)] <- 999

all_bus <- merge(bus_max, fbus_max, by = "zone17", all = TRUE)
all_bus <- all_bus %>%
  mutate(
    maxB = ifelse(maxB < 1.1 & maxB == minB, maxB + 0.1, maxB),
    areaB = round(areaB, 3), areaF = round(areaF)
  ) %>%
  rename(zone = zone17)
all_bus[is.na(all_bus)] <- 999

#8. DISTR file assembly####
sum_cmap <- metra_cmapsum %>%
  left_join(cta_cmapsum, by = "zone") %>%
  left_join(pnr_cmapsum, by = "zone") 
sum_out <- metra_outsum %>%
  left_join(cta_outsum, by = "zone") %>%
  left_join(pnr_outsum, by = "zone") 
sum_all <- sum_cmap %>%
  bind_rows(sum_out) %>%
  left_join(all_bus, by = "zone") %>%
  select(zone, meanDist_m, sd_m, distr_m, 
         meanDist_c, sd_c, distr_c,
         minB, maxB, areaB,
         minF, maxF, areaF,
         meanDist_p, sd_p, distr_p)

sum_all <- sum_all %>%
  mutate(meanDist_c = case_when(meanDist_c <= 19.95 ~ meanDist_c, 
                                meanDist_c > 19.95 ~ 999), 
         sd_c = case_when(meanDist_c == 999 ~ 999, meanDist_c != 999 ~ sd_c),
         distr_c = case_when(meanDist_c == 999 ~ 999, meanDist_c != 999 ~ rlvar)
  ) %>%
  mutate(sd_m = round(sd_m,2),
         sd_c = round(sd_c,2),
         sd_p = round(sd_p,2))


#for HO and NW trips set all feeder bus trips to 999 to remove access
sum_all_NWT <- sum_all %>%
  mutate(
    minF = 999,
    maxF = 999,
    areaF = 999
  )

#8B. export files
write.table(sum_all, "../defaults_base_year/HW_DISTR.TXT", sep = ',', col.names = FALSE, row.names = FALSE)

write.table(sum_all_NWT, "../defaults_base_year/HO_DISTR.TXT", sep = ',', col.names = FALSE, row.names = FALSE)

write.table(sum_all_NWT, "../defaults_base_year/NH_DISTR.TXT", sep = ',', col.names = FALSE, row.names = FALSE)


#9. M01 file assembly####
#9a. Zonal regular bus wait time
#regular busses
bus_am <- itin %>%
  filter(veh >= 25, veh != 30) %>%
  group_by(zone) %>%
  summarise(hdwy_am = mean(hdwy))

bus_mdy <- itin_mdy %>%
  filter(veh_mdy >= 25, veh_mdy != 30) %>%
  group_by(zone) %>%
  summarise(hdwy_mdy = mean(hdwy_mdy))

bwait <- merge(bus_am, bus_mdy, by = "zone", all = T)

#feeder busses
fbus_am <- itin %>%
  filter(veh == 30) %>%
  group_by(zone) %>%
  summarise(fhdwy_am = mean(hdwy))

fbus_mdy <- itin_mdy %>%
  filter(veh_mdy == 30) %>%
  group_by(zone) %>%
  summarise(fhdwy_mdy = mean(hdwy_mdy))

fbwait <- merge(fbus_am, fbus_mdy, by = "zone", all = T)

#9b. Park-n-ride cost and availability
pnr_zn <- pnr %>%
  rename(xi = xcoord, yi = ycoord) %>%
  rename(zoneSt = zone) %>%
  merge(znC, all = TRUE) 

pnr_waitcost <- pnr_zn %>%
  mutate(dist = sqrt( ((xi-xcoord)^2) + ((yi-ycoord)^2) ) ) %>%
  mutate(mdist = dist/5280, pnrT = ifelse(mdist <= 10, 1, 0))%>%
  filter(mdist <= 10) %>%
  group_by(zone)%>%
  slice(which.min(mdist)) %>%
  select(zone, pcost, pnrT)

#9c. supplemental data 
tg <- in5 %>%
  rename(zone = V1, income = V2) %>%
  group_by(zone)

auto <- in6 %>% 
  rename(zone = zone17, j1 = zwkrauto, j2 = zveh, autocc = z_veh_occ)%>%
  mutate(autocc = round(autocc, 2)) %>%
  group_by(zone) %>%
  select(-j1, -j2)

type <- in7 %>%
  rename(zone = Zone) %>%
  group_by(zone)

#9d. finalize data set
M01 <- tg %>%
  left_join(auto, by = "zone") %>%
  left_join(type, by = "zone") %>%
  left_join(bwait, by = "zone") %>%
  left_join(fbwait, by = "zone") %>%
  left_join(pnr_waitcost, by = "zone") %>%
  mutate(hwbus = (case_when(hdwy_am >= 99 ~ 99, is.na(hdwy_am) ~ 99, hdwy_am < 99 ~ round(hdwy_am)))) %>%
  mutate(hwfeed = case_when(fhdwy_am >=99 ~ 99, is.na(fhdwy_am) ~ 99, fhdwy_am < 99 ~ round(fhdwy_am))) %>%
  mutate(hobus = case_when(hdwy_mdy >=99 ~ 99, is.na(hdwy_mdy) ~ 99, hdwy_mdy < 99 ~ round(hdwy_mdy))) %>%
  mutate(hofeed = case_when(fhdwy_mdy  >=99 ~ 99, is.na(fhdwy_mdy ) ~ 99, fhdwy_mdy  < 99 ~ round(fhdwy_mdy))) %>%
  select(zone, Type, pcost, income, pnrT, hwbus, hobus, hwfeed, hofeed, autocc)
M01[is.na(M01)] <- 0

write.table(M01, "../defaults_base_year/ALLPURPOSE_M01.TXT", sep = ',', col.names = FALSE, row.names = FALSE)

