      SUBROUTINE SUB_TRIPGEN6
      IMPLICIT INTEGER(A-Z)
C***********************************************************************
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C***********************************************************************
C
C     THIS IS THE SIXTH PROGRAM IN THE REVISED HOUSEHOLD TRIP
C     GENERATION.  IT ALLOCATES THE PRODUCTIONS AND ATTRACTIONS FOR 
C     NON-HOME BASED TRIP ENDS.  BALANCING OF ATTRACTIONS AND 
C     PRODUCTIONS TAKES PLACE OUTSIDE THE PROGRAM AND REGIONAL
C     TOTALS ARE AN INPUT TO THIS PROGRAM.  THE OUTPUT FILE CONTAINS 
C     THE ATTRACTIONS IN THE 18121 TG SUBZONES/TAZS USED IN THE 
C     PREVIOUS PROGRAMS.
C
C     THIS VERSION IS FOR SUN FORTRAN. 
C
C     EASH, OCTOBER 1995
C
C***********************************************************************
C
C     REVISIONS FOR PRAIRIE PARKWAY TRIP GENERATION IN THIS VERSION.
C     1.  CHANGES IN INPUT-OUTPUT FILE NAMES AND FORMATS
C     2.  DESIGNED FOR SOCIOECONOMIC ZONES PREPARED BY SUHAIL ALCHALABI
C         FOR PRAIRIE PARKWAY (COMBINATION OF TG SUBZONES AND 
C         SECTIONS.
C     3.  OUTPUT FILE NOW CONTAINS BOTH PRODUCTIONS AND ATTRACTIONS 
C         WITHIN TG ZONES
C     
C     EASH, JUNE 2003
C
C***********************************************************************
C
C     REVISED FOR I-290 HOV WORK IN NOVEMBER 2006.  CHANGED TO 
C     ACCOMODATE NEW TEMPORARY FILE FORMATS AND PUMS SUMMARIES.
C
C     EASH, NOVEMBER 2006
C
C***********************************************************************
C
C     REVISED FOR CMAP TRIP GENERATION UPDATE IN JANUARY 2009. 
C     SUBROUTINE REVISED TO ACCOMODATE NEW EXPANDED TRIP CATEGORIES,
C     NEW RATES FOR ALLOCATING TRIP PRODUCTIONS, AND NEW ATTRACTION 
C     INPUT FILE.  HOUSEHOLD AND GROUP QUARTERS ALLOCATION NOW DONE
C     SEPARATELY.  OTHER CHANGES NOTED IN BODY OF SUBROUTINE.
C
C     EASH,  JANUARY 2009
C
C***********************************************************************
C
C     REVISED FOR NEW GROUP QUARTERS INPUTS.
C
C     EASH,  JUNE 2012
C
C***********************************************************************
      INCLUDE 'COMMON_PARAM.FI'
	INCLUDE 'COMMON_GEOG.FI'
      INCLUDE 'COMMON_HHSUMS.FI'
	INCLUDE 'COMMON_ATTR.FI'
	INCLUDE 'COMMON_GQ.FI'
C     
C     MATRICES FOR TRIP TYPES THAT DETERMINE SHARE    
C     OF TOTAL PRODUCTIONS OR ATTRACTIONS ALLOCATED TO Q-SECTION
C
      REAL*8 SHARE(25000,49), HH_PRODS(224,49), GQ_PRODS(33,4), 
     A  SUM_HH(4)
	REAL*8 TOT_SHARE(49)

      CHARACTER*50 HEADER

	REAL*4 HI, ZERO/0.000/
C
C     TRIP ATTRACTION INPUT FILE FROM TG DATABASE IS UNIT 50
C
      OPEN (UNIT=50,FILE='ATTR_IN.TXT',STATUS='OLD',ERR=950) 
C
C     HOUSEHOLD PRODUCTIONS
C
      REWIND 44
C
C     GROUP QUARTERS PRODUCTIONS
C      
	REWIND 45
C
C     LOAD ATTRACTION VARIABLE ARRAYS
C
	WRITE (*,'(/A)') ' SUBZONE PASS TO READ ATTRACTIONS'
	COUNT = 0

   10 CONTINUE   
      READ(50,*,END=19) SZ, R, T, HI
C	
C     INDIANA, WISCONSIN EMPLOYMENT FACTORING
C
      ST = SZ_CO(SZ)/1000

	IF (ST .EQ. 18) THEN
	  R = R * IN_EMPFACT
	  T = T * IN_EMPFACT
      ENDIF
	
	IF (ST .EQ. 55) THEN
	  R = R * WI_EMPFACT
	  T = T * WI_EMPFACT
      ENDIF
C
	COUNT = COUNT + 1
      WRITE (*,'(A,I6)') ' TG SUBZONE= ', SZ
C
      SZ_RETEMP(SZ) = R
      SZ_TOTEMP(SZ) = T
	SZ_NRETEMP(SZ) = T - R
	
	IF (SZ_NRETEMP(SZ) .LT. 0) THEN

        WRITE (16,'(/A)') 'ERROR:  RETAIL EMP GT TOTAL EMP' 
        WRITE (16,'(I6,A)') SZ,' RETAIL EMP SET EQUAL TO TOTAL EMP'
        SZ_RETEMP(SZ) = T
	  SZ_NRETEMP(SZ) = 0
	   
      ENDIF

      SZ_HINC(SZ) = HI
	SZ_HIEMP(SZ) = SZ_TOTEMP(SZ) * HI
	SZ_LIEMP(SZ) = SZ_TOTEMP(SZ) * (1.00-HI)

	GO TO 10
C
   19	CONTINUE
C
C     ACCUMULATE INPUTS
C
      DO SZ=1,SUBZONES
	  DO J=1,COUNTIES
	    IF (SZ_CO(SZ) .EQ. CO_NUM(J)) ICO = J
	  ENDDO

        DO J=1,PUMA1
	    IF (SZ_PUMA1(SZ) .EQ. P1_NUM(J)) IP1 = J
	  ENDDO

        DO J=1,PUMA5
	    IF (SZ_PUMA5(SZ) .EQ. P5_NUM(J)) IP5 = J
	  ENDDO

	  ICHI = SZ_CHI(SZ)
	  ICBD = SZ_CBD(SZ)

	  CO_HH(ICO) = CO_HH(ICO) + SZ_HH(SZ)
        P1_HH(IP1) = P1_HH(IP1) + SZ_HH(SZ)
	  P5_HH(IP5) = P5_HH(IP5) + SZ_HH(SZ) 
	  REG_HH = REG_HH + SZ_HH(SZ)
	  IF (ICHI .GT. 0) CHI_HH = CHI_HH + SZ_HH(SZ)
	  IF (ICBD .GT. 0) CBD_HH = CBD_HH + SZ_HH(SZ) 

	  CO_RETEMP(ICO) = CO_RETEMP(ICO) + SZ_RETEMP(SZ)
        P1_RETEMP(IP1) = P1_RETEMP(IP1) + SZ_RETEMP(SZ)
	  P5_RETEMP(IP5) = P5_RETEMP(IP5) + SZ_RETEMP(SZ) 
	  REG_RETEMP = REG_RETEMP + SZ_RETEMP(SZ)
	  IF (ICHI .GT. 0) CHI_RETEMP = CHI_RETEMP + SZ_RETEMP(SZ)
	  IF (ICBD .GT. 0) CBD_RETEMP = CBD_RETEMP + SZ_RETEMP(SZ) 

	  CO_LIEMP(ICO) = CO_LIEMP(ICO) + SZ_LIEMP(SZ)
        P1_LIEMP(IP1) = P1_LIEMP(IP1) + SZ_LIEMP(SZ)
	  P5_LIEMP(IP5) = P5_LIEMP(IP5) + SZ_LIEMP(SZ) 
	  REG_LIEMP = REG_LIEMP + SZ_LIEMP(SZ)
	  IF (ICHI .GT. 0) CHI_LIEMP = CHI_LIEMP + SZ_LIEMP(SZ)
	  IF (ICBD .GT. 0) CBD_LIEMP = CBD_LIEMP + SZ_LIEMP(SZ) 

	  CO_HIEMP(ICO) = CO_HIEMP(ICO) + SZ_HIEMP(SZ)
        P1_HIEMP(IP1) = P1_HIEMP(IP1) + SZ_HIEMP(SZ)
	  P5_HIEMP(IP5) = P5_HIEMP(IP5) + SZ_HIEMP(SZ) 
	  REG_HIEMP = REG_HIEMP + SZ_HIEMP(SZ)
	  IF (ICHI .GT. 0) CHI_HIEMP = CHI_HIEMP + SZ_HIEMP(SZ)
	  IF (ICBD .GT. 0) CBD_HIEMP = CBD_HIEMP + SZ_HIEMP(SZ) 

	  CO_NRETEMP(ICO) = CO_NRETEMP(ICO) + SZ_NRETEMP(SZ)
        P1_NRETEMP(IP1) = P1_NRETEMP(IP1) + SZ_NRETEMP(SZ)
	  P5_NRETEMP(IP5) = P5_NRETEMP(IP5) + SZ_NRETEMP(SZ) 
	  REG_NRETEMP = REG_NRETEMP + SZ_NRETEMP(SZ)
	  IF (ICHI .GT. 0) CHI_NRETEMP = CHI_NRETEMP + SZ_NRETEMP(SZ)
	  IF (ICBD .GT. 0) CBD_NRETEMP = CBD_NRETEMP + SZ_NRETEMP(SZ) 

	  CO_TOTEMP(ICO) = CO_TOTEMP(ICO) + SZ_TOTEMP(SZ)
        P1_TOTEMP(IP1) = P1_TOTEMP(IP1) + SZ_TOTEMP(SZ)
	  P5_TOTEMP(IP5) = P5_TOTEMP(IP5) + SZ_TOTEMP(SZ) 
	  REG_TOTEMP = REG_TOTEMP + SZ_TOTEMP(SZ)
	  IF (ICHI .GT. 0) CHI_TOTEMP = CHI_TOTEMP + SZ_TOTEMP(SZ)
	  IF (ICBD .GT. 0) CBD_TOTEMP = CBD_TOTEMP + SZ_TOTEMP(SZ) 

      ENDDO
C
C     FOLLOWING ACCUMULATED VARIABLES CONTAIN REGIONAL PRODUCTION AND 
C     ATTRACTION TRIP ENDS TO BE ALLOCATED.
C
	WRITE (*,'(/A)') ' SUBZONE PASS TO READ PRODUCTIONS'
	COUNT = 0

   30 CONTINUE

      READ (44,'(I6,200F12.4)',END=39) SZ, (SUM_HH(I),I=1,4),
     A  ((HH_PRODS(I,J),J=1,4),I=1,49)

      READ (45,'(I6,132F12.4)',END=39) SZ1, 
     A (GQ_PRODS(I,1),GQ_PRODS(I,2),GQ_PRODS(I,3),GQ_PRODS(I,4),I=1,33)
      
	COUNT = COUNT + 1

	IF (SZ .NE. SZ1) GO TO 952
	IF (SZ .NE. COUNT) GO TO 953
C
C     ACCUMULATE WORKER HOUSEHOLD PRODUCTIONS AT HOME END
C
      DO I=1,4      
	  DO T=1,7
	    SZ_PRODS(SZ,T) = SZ_PRODS(SZ,T) + HH_PRODS(T,I)
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO
C
C     NEXT NONWORKERS
C
        DO T=21,24
	    SZ_PRODS(SZ,T) = SZ_PRODS(SZ,T) + HH_PRODS(T,I)
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO
C
C     NEXT CHILDREN 12-15
C
	  DO T=34,37
	    SZ_PRODS(SZ,T) = SZ_PRODS(SZ,T) + HH_PRODS(T,I)
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO
C
C     REMAINING REGIONAL PRODUCTIONS
C
        DO T=8,20     	
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO

        DO T=25,33     	
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO
        
	  DO T=38,49     	
	    REG_PRODS(T) = REG_PRODS(T) + HH_PRODS(T,I)
        ENDDO
	ENDDO
C
C     REPEAT FOR GROUP QUARTERS FOR WORKERS (ONLY VEHICLE TRIPS)
C
      DO I=1,4
	  SZ_GQ_PRODS(SZ,1) = SZ_GQ_PRODS(SZ,1) + GQ_PRODS(1,I)
        REG_GQ_PRODS(1) = REG_GQ_PRODS(1) + GQ_PRODS(1,I)

	  DO T=3,7
	    SZ_GQ_PRODS(SZ,T) = SZ_GQ_PRODS(SZ,T) + GQ_PRODS(T,I)
	    REG_GQ_PRODS(T) = REG_GQ_PRODS(T) + GQ_PRODS(T,I)
        ENDDO
C
C     NEXT NONWORKERS
C
        DO T=21,24
	    SZ_GQ_PRODS(SZ,T) = SZ_GQ_PRODS(SZ,T) + GQ_PRODS(T,I) 
	    REG_GQ_PRODS(T) = REG_GQ_PRODS(T) + GQ_PRODS(T,I) 
        ENDDO
C
C     REMAINING REGIONAL PRODUCTIONS
C
        DO T=8,20     	
	    REG_GQ_PRODS(T) = REG_GQ_PRODS(T) + GQ_PRODS(T,I)
        ENDDO

        DO T=25,33     	
	    REG_GQ_PRODS(T) = REG_GQ_PRODS(T) + GQ_PRODS(T,I)
        ENDDO
      ENDDO  

	GO TO 30
	
   39 CONTINUE
C
C     CALCULATE PRODUCTION SHARES FOR NONHOME PRODUCTIONS
C
      DO SZ=1,SUBZONES
C
C     WORKERS
C
C     WORK TO NONHOME/WORK, HOME (PRODS(8,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,8) = 0.018 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,8) = 0.018 * SZ_TOTEMP(SZ)
        ENDIF
C
C     WORK TO NONHOME/WORK, NONHOME (PRODS(9,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,9) = 0.399 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,9) = 0.217 * SZ_TOTEMP(SZ)
        ENDIF
C
C     WORK TO SHOP (PRODS(10,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,10) = 0.087 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,10) = 0.070 * SZ_TOTEMP(SZ)
        ENDIF
C
C     WORK TO WORK (PRODS(11,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,11) = 0.093 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,11) = 0.140 * SZ_TOTEMP(SZ)
        ENDIF
C
C     NONHOME/WORK, HOME TO NONHOME/WORK, HOME (PRODS(12,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,12) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,12) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME/WORK, HOME TO NONHOME/WORK, NONHOME (PRODS(13,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,13) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,13) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME/WORK, HOME TO SHOP (PRODS(14,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,14) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,14) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME/WORK, NONHOME TO NONHOME/WORK, HOME (PRODS(15,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,15) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,15) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME/WORK, NONHOME TO NONHOME/WORK, NONHOME (PRODS(16,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,16) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,16) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME/WORK, NONHOME TO SHOP (PRODS(17,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,17) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,17) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO NONHOME/WORK, HOME (PRODS(18,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,18) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,18) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME/WORK, NONHOME (PRODS(19,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,19) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,19) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO SHOP (PRODS(20,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,20) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,20) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONWORKERS
C
C     NONHOME, HOME TO NONHOME, HOME (PRODS(25,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,25) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,25) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, NONHOME (PRODS(26,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,26) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,26) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO SHOP (PRODS(27,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,27) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,27) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, HOME (PRODS(28,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,28) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,28) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, NONHOME (PRODS(29,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,29) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,29) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO SHOP (PRODS(30,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,30) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,30) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO NONHOME, HOME (PRODS(31,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,31) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,31) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME, NONHOME (PRODS(32,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,32) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,32) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO SHOP (PRODS(33,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,33) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,33) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     CHILDREN 12 TO 15
C
C     SCHOOL TO NONHOME, HOME (PRODS(38,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,38) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,38) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     SCHOOL TO NONHOME, NONHOME (PRODS(39,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,39) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,39) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     SCHOOL TO SHOP (PRODS(40,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,40) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,40) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, HOME TO NONHOME, HOME (PRODS(41,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,41) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,41) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, NONHOME (PRODS(42,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,42) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,42) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO SHOP (PRODS(43,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,43) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,43) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, HOME (PRODS(44,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,44) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,44) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, NONHOME 
C     (PRODS(45,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,45) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,45) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO SHOP (PRODS(46,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,46) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,46) = 1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO NONHOME, HOME (PRODS(47,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,47) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,47) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME, NONHOME (PRODS(48,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,48) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,48) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO SHOP (PRODS(49,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,49) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,49) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
      ENDDO
C
C     TOTAL UP SHARES
C
      DO T=1,49
	  TOT_SHARE(T) = 0.00 
	ENDDO       
	
	DO SZ=1,SUBZONES
	  DO T=8,20
	    TOT_SHARE(T) = TOT_SHARE(T) + SHARE(SZ,T)
        ENDDO

	  DO T=25,33
	    TOT_SHARE(T) = TOT_SHARE(T) + SHARE(SZ,T)
        ENDDO

	  DO T=38,49
	    TOT_SHARE(T) = TOT_SHARE(T) + SHARE(SZ,T)
        ENDDO
	ENDDO
C
C     ALLOCATE NONHOME PRODUCTIONS
C
	DO SZ=1,SUBZONES
	  DO T=8,20
          SZ_PRODS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_PRODS(T)
          SZ_GQ_PRODS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_GQ_PRODS(T)
        ENDDO

	  DO T=25,33
          SZ_PRODS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_PRODS(T)
	    SZ_GQ_PRODS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_GQ_PRODS(T)
        ENDDO

	  DO T=38,49
          SZ_PRODS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_PRODS(T)
        ENDDO
      ENDDO
C
C     CALCULATE ATTRACTION SHARES
C
	DO T=1,49
	  DO SZ=1,SUBZONES
	    SHARE(SZ,T) = 0.00
        ENDDO
	  TOT_SHARE(T) = 0.00

	  REG_ATTRS(T) = REG_PRODS(T)
      ENDDO

      DO SZ=1,SUBZONES
C
C     WORKERS
C
C    	HOME TO LOW INCOME WORKPLACE (ATTRS(1,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,1) = 1.307 * SZ_TOTEMP(SZ) * (1.00-SZ_HINC(SZ))
	  ELSE
	    SHARE(SZ,1) = 0.975 * SZ_TOTEMP(SZ) * (1.00-SZ_HINC(SZ))
        ENDIF
C
C    	HOME TO HIGH INCOME WORKPLACE (ATTRS(2,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,2) = 1.307 * SZ_TOTEMP(SZ) * SZ_HINC(SZ)
	  ELSE
	    SHARE(SZ,2) = 0.975 * SZ_TOTEMP(SZ) * SZ_HINC(SZ)
        ENDIF
C
C    	HOME TO WORK RELATED (ATTRS(3,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,3) = 
     A      1.162*(0.509*SZ_RETEMP(SZ) + 0.046*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,3) = 
     A      1.058*(0.528*SZ_RETEMP(SZ) + 0.070*SZ_NRETEMP(SZ))
        ENDIF
C
C     HOME TO SCHOOL (ATTRS(4,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,4) = 
     A      1.286*(2.597*SZ_RETEMP(SZ) + 0.053*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,4) = 
     A      1.076*(3.605*SZ_RETEMP(SZ) + 0.201*SZ_NRETEMP(SZ))
        ENDIF
C
C    	HOME TO NONHOME/WORK, HOME (ATTRS(5,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,5) = 0.363 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,5) = 0.170 * SZ_HH(SZ)
        ENDIF
C
C    	HOME TO NONHOME/WORK, NONHOME (ATTRS(6,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,6) = 
     A      1.286*(2.597*SZ_RETEMP(SZ) + 0.053*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,6) = 
     A      1.076*(3.605*SZ_RETEMP(SZ) + 0.201*SZ_NRETEMP(SZ))
        ENDIF
C
C    	HOME TO SHOP (ATTRS(7,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,7) = 0.891 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,7) = 2.127 * SZ_RETEMP(SZ)
        ENDIF
C
C     WORK TO NONHOME/WORK, HOME (ATTRS(8,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,8) = 0.129 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,8) = 0.025 * SZ_HH(SZ)
        ENDIF
C
C     WORK TO NONHOME/WORK, NONHOME (ATTRS(9,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,9) = 
     A      1.083*(0.421*SZ_RETEMP(SZ) + 0.302*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,9) = 
     A      1.091*(0.847*SZ_RETEMP(SZ) + 0.107*SZ_NRETEMP(SZ))
        ENDIF
C
C     WORK TO SHOP (ATTRS(10,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,10) = 1.224 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,10) = 0.454 * SZ_RETEMP(SZ)
        ENDIF
C
C     WORK TO WORK (ATTRS(11,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,11) = 0.093 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,11) = 0.140 * SZ_TOTEMP(SZ)
        ENDIF
C
C     NONHOME/WORK, HOME TO NONHOME/WORK, HOME (ATTRS(12,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,12) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,12) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME/WORK, HOME TO NONHOME/WORK, NONHOME (ATTRS(13,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,13) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,13) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME/WORK, HOME TO SHOP (ATTRS(14,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,14) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,14) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONHOME/WORK, NONHOME TO NONHOME/WORK, HOME (ATTRS(15,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,15) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,15) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME/WORK, NONHOME TO NONHOME/WORK, NONHOME (ATTRS(16,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,16) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,16) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME/WORK, NONHOME TO SHOP (ATTRS(17,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,17) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,17) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME/WORK, HOME (ATTRS(18,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,18) = 0.109 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,18) = 0.062 * SZ_HH(SZ)
        ENDIF
C
C     SHOP TO NONHOME/WORK, NONHOME (ATTRS(19,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,19) = 
     A      1.156*(1.376*SZ_RETEMP(SZ) + 0.015*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,19) = 
     A      1.185*(1.144*SZ_RETEMP(SZ) + 0.054*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO SHOP (ATTRS(20,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,20) = 0.684 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,20) = 1.070 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONWORKERS
C
C     HOME TO SCHOOL (ATTRS(21,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,21) = 0.190 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,21) = 
     A      1.203*(2.951*SZ_RETEMP(SZ) + 0.221*SZ_NRETEMP(SZ))
        ENDIF
C
C    	HOME TO NONHOME/WORK, HOME (ATTRS(22,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,22) = 0.100 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,22) = 0.197 * SZ_HH(SZ)
        ENDIF
C
C    	HOME TO NONHOME/WORK, NONHOME (ATTRS(23,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,23) = 0.190 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,23) = 
     A      1.203*(2.951*SZ_RETEMP(SZ) + 0.221*SZ_NRETEMP(SZ))
        ENDIF
C
C    	HOME TO SHOP (ATTRS(24,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,24) = 0.545 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,24) = 2.218 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, HOME (ATTRS(25,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,25) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,25) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, NONHOME (ATTRS(26,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,26) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,26) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, HOME TO SHOP (ATTRS(27,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,27) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,27) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, HOME (ATTRS(28,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,28) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,28) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, NONHOME (ATTRS(29,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,29) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,29) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO SHOP (ATTRS(30,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,30) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,30) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME, HOME (ATTRS(31,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,31) = 0.050 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,31) = 0.053 * SZ_HH(SZ)
        ENDIF
C
C     SHOP TO NONHOME, NONHOME (ATTRS(32,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,32) = 
     A      1.123*(0.932*SZ_RETEMP(SZ) + 0.005*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,32) = 
     A      1.209*(1.266*SZ_RETEMP(SZ) + 0.012*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO SHOP (ATTRS(33,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,33) = 0.472 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,33) = 1.119 * SZ_RETEMP(SZ)
        ENDIF
C
C     CHILDREN 12 TO 15
C
C     HOME TO SCHOOL (ATTRS(34,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,34) =      
     A      0.651*(0.989*SZ_RETEMP(SZ) + 0.009*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,34) = 
     A      1.265*(2.645*SZ_RETEMP(SZ) + 0.184*SZ_NRETEMP(SZ))
        ENDIF
C
C     HOME TO NONHOME, HOME (ATTRS(35,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,35) = 0.152 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,35) = 0.134 * SZ_HH(SZ)
        ENDIF
C
C     HOME TO NONHOME, NONHOME (ATTRS(36,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,36) =      
     A      0.651*(0.989*SZ_RETEMP(SZ) + 0.009*SZ_NRETEMP(SZ))
	  ELSE
	    SHARE(SZ,36) = 
     A      1.265*(2.645*SZ_RETEMP(SZ) + 0.184*SZ_NRETEMP(SZ))
        ENDIF
C
C     HOME TO SHOP (ATTRS(37,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,37) = 0.073 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,37) = 0.820 * SZ_RETEMP(SZ)
        ENDIF
C
C     SCHOOL TO NONHOME, HOME (ATTRS(38,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,38) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,38) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     SCHOOL TO NONHOME, NONHOME (ATTRS(39,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,39) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,39) = 
     A      1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     SCHOOL TO SHOP (ATTRS(40,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,40) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,40) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, HOME (ATTRS(41,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,41) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,41) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, HOME TO NONHOME, NONHOME (ATTRS(42,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,42) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,42) = 
     A      1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, HOME TO SHOP (ATTRS(43,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,43) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,43) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, HOME (ATTRS(44,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,44) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,44) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     NONHOME, NONHOME TO NONHOME, NONHOME  (ATTRS(45,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,45) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,45) = 
     A      1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     NONHOME, NONHOME TO SHOP (ATTRS(46,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,46) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,46) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
C
C     SHOP TO NONHOME, HOME (ATTRS(47,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,47) = 0.019 * SZ_HH(SZ)
	  ELSE
	    SHARE(SZ,47) = 0.036 * SZ_HH(SZ)
        ENDIF
C
C     SHOP TO NONHOME, NONHOME (ATTRS(48,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,48) = 0.011 * SZ_TOTEMP(SZ)
	  ELSE
	    SHARE(SZ,48) = 
     A      1.241*(0.633*SZ_RETEMP(SZ) + 0.018*SZ_NRETEMP(SZ))
        ENDIF
C
C     SHOP TO SHOP (ATTRS(49,))
C
	  IF (SZ_CBD(SZ) .GT. 0) THEN 
	    SHARE(SZ,49) = 0.042 * SZ_RETEMP(SZ)
	  ELSE
	    SHARE(SZ,49) = 0.346 * SZ_RETEMP(SZ)
        ENDIF
      ENDDO
C
C     TOTAL UP SHARES
C
      DO T=1,49
	  TOT_SHARE(T) = 0.00 
	ENDDO       
	
	DO SZ=1,SUBZONES
	  DO T=1,49
	    TOT_SHARE(T) = TOT_SHARE(T) + SHARE(SZ,T)
        ENDDO
	ENDDO
C
C     ALLOCATE ATTRACTIONS
C
	DO SZ=1,SUBZONES
	  DO T=1,49
          SZ_ATTRS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_PRODS(T)
        ENDDO
      ENDDO
C
	DO SZ=1,SUBZONES
        SZ_GQ_ATTRS(SZ,1) = (SHARE(SZ,1)/TOT_SHARE(1))*REG_GQ_PRODS(1)        

	  DO T=3,33
          SZ_GQ_ATTRS(SZ,T) = (SHARE(SZ,T)/TOT_SHARE(T))*REG_GQ_PRODS(T)        
        ENDDO
      ENDDO
C	          
	GO TO 999
C
  950 WRITE (*,'(/A)')  'ERROR:  PROBLEM OPENING ATTR_IN.TXT'
      STOP 950

  951 WRITE (*,'(/A)')  'ERROR:  PROBLEM OPENING FILE FIRST_PA_OUT.TXT'
      STOP 951

  952 WRITE (*,'(/A)')  'ERROR:  SUBZONES ON HOUSEHOLD AND GROUP'
      WRITE (*,'(A,2I6)') 'QUARTERS PRODUCTION FILES MISMATCH', SZ, SZ1
      STOP 952

  953 WRITE (*,'(/A)')  'ERROR:  SUBZONES ON HOUSEHOLD AND GROUP'
      WRITE (*,'(A,2I6)') 'QUARTERS PRODUCTION OUT OF ORDER', SZ, SZ1
      STOP 953
C
  999 CONTINUE
C
C     PRINT ROW AND COLUMN TOTALS FOR CHECKING
C
	WRITE(16,'(/A)')   'HOUSEHOLD-EMPLOYMENT ATTRACTION SUMMARIES'
	WRITE (16,'(/A)')  'COUNTIES'
	WRITE (16,'(/A)')  '                                 EMPLOYMENT'
	WRITE (16,'(A)')   '                ------------------------------
     A---------------'       
	WRITE (16,'(A)')   ' COUNTY   HHOLDS   RETAIL   NONRET   <$ INC   
     A>$ INC    TOTAL'
	WRITE (16,'(A)')   '----------------------------------------------
     A---------------'       
	
	DO I=1,COUNTIES
	  WRITE (16,'(I7,3I9,2F9.0,I9)') CO_NUM(I), CO_HH(I), CO_RETEMP(I), 
     A    CO_NRETEMP(I), CO_LIEMP(I), CO_HIEMP(I), CO_TOTEMP(I)
	ENDDO

	WRITE (16,'(A,3I9,2F9.0,I9)')  '  TOTAL', REG_HH, REG_RETEMP, 
     A  REG_NRETEMP, REG_LIEMP, REG_HIEMP, REG_TOTEMP
	WRITE (16,'(/A,3I9,2F9.0,I9)') 'CHICAGO', CHI_HH, CHI_RETEMP, 
     A  CHI_NRETEMP, CHI_LIEMP, CHI_HIEMP, CHI_TOTEMP
	WRITE (16,'(A,3I9,2F9.0,I9)')  'CHI CBD', CBD_HH, CBD_RETEMP, 
     A  CBD_NRETEMP, CBD_LIEMP, CBD_HIEMP, CBD_TOTEMP
C
	WRITE (16,'(/A)')  'ONE PERCENT PUMAS'
	WRITE (16,'(/A)')  '                                 EMPLOYMENT'
	WRITE (16,'(A)')   '                ------------------------------
     A---------------'       
	WRITE (16,'(A)')   ' COUNTY   HHOLDS   RETAIL   NONRET   <$ INC   
     A>$ INC    TOTAL'
	WRITE (16,'(A)')   '----------------------------------------------
     A---------------'       

	DO I=1,PUMA1
	  WRITE (16,'(I7,3I9,2F9.0,I9)') P1_NUM(I), P1_HH(I), P1_RETEMP(I), 
     A    P1_NRETEMP(I), P1_LIEMP(I), P1_HIEMP(I), P1_TOTEMP(I)
	ENDDO

	WRITE (16,'(A,3I9,2F9.0,I9)')  '  TOTAL', REG_HH, REG_RETEMP, 
     A  REG_NRETEMP, REG_LIEMP, REG_HIEMP, REG_TOTEMP
C
	WRITE (16,'(/A)')  'FIVE PERCENT PUMAS'
	WRITE (16,'(/A)')  '                                 EMPLOYMENT'
	WRITE (16,'(A)')   '                ------------------------------
     A---------------'       
	WRITE (16,'(A)')   ' COUNTY   HHOLDS   RETAIL   NONRET   <$ INC   
     A>$ INC    TOTAL'
	WRITE (16,'(A)')   '----------------------------------------------
     A---------------'       

	DO I=1,PUMA5
	  WRITE (16,'(I7,3I9,2F9.0,I9)') P5_NUM(I), P5_HH(I), P5_RETEMP(I), 
     A    P5_NRETEMP(I), P5_LIEMP(I), P5_HIEMP(I), P5_TOTEMP(I)
	ENDDO

	WRITE (16,'(A,3I9,2F9.0,I9)')  '  TOTAL', REG_HH, REG_RETEMP, 
     A  REG_NRETEMP, REG_LIEMP, REG_HIEMP, REG_TOTEMP
C
C     OPTION TO OUTPUT FORMATED FILE OF PRODUCTIONS AND ATTRACTIONS
C
      IF (SAVE_FILE) THEN
C
C     INITIAL FILE OF PRODUCTIONS AND ATTRACTIONS IN 49 CATEGORIES
C     IS UNIT 51  
C
        OPEN (UNIT=51,FILE='FIRST_PA_OUT.TXT',STATUS='NEW',ERR=951)

	  DO T=1,33
	    DO SZ = 1,SUBZONES
            WRITE (51,'(2I6,I2,4F9.1)')  SZ, SZ_ZONE(SZ), T, 
     A        SZ_PRODS(SZ,T), SZ_ATTRS(SZ,T), SZ_GQ_PRODS(SZ,T), 
     B        SZ_GQ_ATTRS(SZ,T)
	    ENDDO
        ENDDO
C
	  DO T=34,49
	    DO SZ = 1,SUBZONES
            WRITE (51,'(2I6,I2,4F9.1)')  SZ, SZ_ZONE(SZ), T, 
     A        SZ_PRODS(SZ,T), SZ_ATTRS(SZ,T), ZERO, ZERO
	    ENDDO
        ENDDO
        CLOSE (51,DISP='KEEP')
      ENDIF
C
C     FINISH UP
C
	CLOSE (50,DISP='KEEP')
C    
	IF (SAVE_FILE) THEN
	  CLOSE (44,DISP='KEEP')
      ELSE
	  CLOSE (44,DISP='DELETE')
	ENDIF
C
      IF (SAVE_FILE) THEN
        CLOSE (45,DISP='KEEP')
      ELSE
	  CLOSE (45,DISP='DELETE')
      ENDIF
C
      WRITE (16,'(/A)') ' END OF TRIPGEN6'
      WRITE (*,'(/A)') ' END OF TRIPGEN6'

	RETURN
      END