      SUBROUTINE SUB_PUMS
      IMPLICIT INTEGER(A-Z)
C***********************************************************************
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C***********************************************************************
C
C     THIS SUBROUTINE READS A FILE OF HOUSEHOLDS FROM THE 
C     PUMS_HHTAB_IN.TXT FILE.  IT SETS UP A TABLE DIMENSIONED FOR 624 
C     DIFFERENT HOUSEHOLD TYPES IN ONE OF FOUR SUMMARY AREAS AS SHOWN
C     IN COMMON ROW-COL.  EACH CELL HAS THE NUMBER OF WEIGHTED 
C     HOUSEHOLDS CROSS-CLASSIFIED AS SHOWN BELOW.
C
C     FRACTIONS OF HOUSEHOLDS IN EACH CATEGORY ARE THEN CALCULATED.
C
C     HOUSEHOLD TYPES ARE DEFINED BY
C
C       ADULT CATEGORIES (16+) x4 (1,2,3,4+)
C       WORKER CATEGORIES (ACS PUMS COW=1,8) x4 (0,1,2,3+)
C       CHILDEN (0-15) x4 (0,1,2,3+)
C       INCOME QUARTILES x4 (1,2,4,4)
C       AGE OF HOUSEHOLD HEAD x3 (LESS THAN 35, 35-64, 65+)
C
C     DEFINITION OF INCOME QUARTILES USED FOR THE COMBINED 
C     2006-2010 PUMS_HHTAB_IN.TXT FILE.  INCOMES ARE AJUSTED TO 2010
C     USING THE ADJINC VARIABLE IN THE ACS PUMS HH DATA.
C
C     2010 DOLLARS
C
C       1 = LESS THAN $30,200
C       2 = $30,201 TO $59,400
C       3 = $59,401 TO $100,900
C       4 = MORE THAN $100,900
C
C     HOUSEHOLD TYPE DEFINITIONS
C
C       INCOME QUARTILE 1, HOUSEHOLDER UNDER 35
C
C            HHTYPE
C        CHILDREN 0-15
C        0   1   2   3+  WORKERS  ADULTS  INC QUARTILE  HOUSEHOLDER
C       -------------------------------------------------------------
C        1  14  27  40      0        1          1            1
C        2  15  28  41      0        2          1            1   
C        3  16  29  42      0        3          1            1            
C        4  17  30  43      0        4+         1            1
C        5  18  31  44      1        1          1            1
C        6  19  32  45      1        2          1            1
C        7  20  33  46      1        3          1            1
C        8  21  34  47      1        4+         1            1
C        9  22  35  48      2        2          1            1
C       10  23  36  49      2        3          1            1
C       11  24  37  50      2        4+         1            1
C       12  25  38  51      3+       3          1            1
C       13  26  39  52      3+       4+         1            1
C
C       INCOME QUARTILE 2, HOUSEHOLDER UNDER 35 (ADD 52 TO ABOVE)
C
C       INCOME QUARTILE 3, HOUSEHOLDER UNDER 35 (ADD 104 TO ABOVE)
C 
C       INCOME QUARTILE 4, HOUSEHOLDER UNDER 35 (ADD 156 TO ABOVE)
C
C       INCOME QUARTILE 1, HOUSEHOLDER 35-64 (ADD 208 TO ABOVE)
C
C       INCOME QUARTILE 2, HOUSEHOLDER 35-64 (ADD 260 TO ABOVE)
C
C       INCOME QUARTILE 3, HOUSEHOLDER 35-64 (ADD 312 TO ABOVE)
C
C       INCOME QUARTILE 4, HOUSEHOLDER 35-64 (ADD 364 TO ABOVE)
C
C       INCOME QUARTILE 1, HOUSEHOLDER 65+ (ADD 416 TO ABOVE)
C
C       INCOME QUARTILE 2, HOUSEHOLDER 65+ (ADD 468 TO ABOVE)
C
C       INCOME QUARTILE 3, HOUSEHOLDER 65+ (ADD 520 TO ABOVE)
C
C       INCOME QUARTILE 4, 65+ (ADD 572 TO ABOVE)
C
C***********************************************************************
      INCLUDE 'COMMON_HHSUMS.FI'
      INCLUDE 'COMMON_GEOG.FI'
      INCLUDE 'COMMON_PARAM.FI'
      INCLUDE 'COMMON_CONTROL.FI'
      INCLUDE 'ROW_COL.FI'
      
      REAL*4 H_WINC 
C
C     OPEN PUMS HOUSEHOLD TYPE TABLE
C
      OPEN (UNIT=19,FILE='PUMS_HHTYPE_IN.TXT',STATUS='OLD',ERR=198)
C
C     OPEN TABLE OF CROSS CLASSIFIED PUMS HOUSEHOLDS
C
	OPEN (UNIT=18,FILE='PUMS_HHTAB_IN.TXT',STATUS='OLD',ERR=199)
C
C     LOAD DIRECTORY OF HH TYPES
C
    3 READ (19,*,END=7) HHT, ADULT, WORKER, CHILD, IQUARTILE, HHOLDER
      
      HHT_ADULT(HHT) = ADULT
      HHT_WORKER(HHT) = WORKER
      HHT_CHILD(HHT) = CHILD
      HHT_INC4(HHT) = IQUARTILE
      HHT_HHOLDER(HHT) = HHOLDER
      
      GO TO 3
    7 CONTINUE
C
C     PRINT HOUSEHOLD TYPES
C
     	WRITE (16,'(/A)') 'HOUSEHOLD TYPES IN TRIP GENERATION MODEL'      

      WRITE (16,'(/A)')'            HOUSEHOLD SIZE'

      WRITE (16,'(A)') '  HH   -----------------------  INCOME  HHOLDER'
      WRITE (16,'(A)') ' CODE  ADULTS WORKERS CHILDREN   QUART    CODE'
      WRITE (16,'(A)') '-----------------------------------------------'
      DO HHT=1,624
        WRITE (16,'(I4,2I7,3I9)') HHT, HHT_ADULT(HHT), HHT_WORKER(HHT),
     A    HHT_CHILD(HHT), HHT_INC4(HHT), HHT_HHOLDER(HHT)
      ENDDO  
C
C-- Heither, 03-13-2018: file not needed with PopSyn procedures so skip this
C     LOAD REGIONAL PUMS HOUSEHOLD TABLES
C
	GO TO 99
   15 READ (18,*,END=49) HHT, HH, RC1

      IF (HHT .GT. 624) GO TO 299
      
      IF (PUMS_HH(HHT,RC1) .GT. 0) GO TO 399
      IF (RC1 .GT. 4) GO TO 499

	PUMS_HH(HHT,RC1) = HH
            
	GO TO 15

   49 CONTINUE
C
C     TOTAL HOUSEHOLDS IN PUMS
C
      DO RC = 1,4 
        DO HHT = 1,624
          PUMS_TOT = PUMS_TOT + PUMS_HH(HHT,RC)
          PUMS_TOTRC(RC) = PUMS_TOTRC(RC) + PUMS_HH(HHT,RC)
        ENDDO  
      ENDDO
C
C     TOTAL ROWS AND COLUMNS FROM PUMS TABLE
C
	DO RC = 1,4
        DO HHT=1,624
          I = HHT_ADULT(HHT) 
          PUMS_ADULT(I) = PUMS_ADULT(I) + PUMS_HH(HHT,RC)
      
          I = HHT_WORKER(HHT) + 1
          PUMS_WORKER(I) = PUMS_WORKER(I) + PUMS_HH(HHT,RC)
      
          I = HHT_CHILD(HHT) + 1 
          PUMS_CHILD(I) = PUMS_CHILD(I) + PUMS_HH(HHT,RC)
      
          I = HHT_INC4(HHT)
          PUMS_INCOME(I) = PUMS_INCOME(I) + PUMS_HH(HHT,RC)
      
          I = HHT_HHOLDER(HHT)
          PUMS_HHOLDER(I) = PUMS_HHOLDER(I) + PUMS_HH(HHT,RC)
        ENDDO  
      ENDDO  
C
C     PRINT ROW AND COLUMN TOTALS FOR CHECKING, PUMS INPUT
     	WRITE (16,'(/A)') 'ROW-COLUMN HOUSEHOLD TOTALS:  PUMS_INPUT.TXT'
      WRITE (16,'(A)')  '--------------------------------------------'
      WRITE (16,'(A,I8)')'  TOTAL HOUSEHOLDS = ', PUMS_TOT
      WRITE (16,'(A,4I8)') '  HHS BY ADULTS (1,2,3,4+) =',
     A  PUMS_ADULT
      WRITE (16,'(A,4I8)') '  HHS BY WORKERS (0,1,2,3+) =', PUMS_WORKER
      WRITE (16,'(A,4I8)') '  HHS BY 0 TO 15 YR CHILDREN (0,1,2,3+) =',
     A  PUMS_CHILD
	WRITE (16,'(A,4I8)') '  HHS BY INCOME QUARTILE =',PUMS_INCOME
	WRITE (16,'(A,3I8)') '  HHS BY HOUSEHOLDER AGE (LESS THAN 35,36-64,65+)
     A =', PUMS_HHOLDER
   
	CLOSE (18,DISP='KEEP')
      CLOSE (19,DISP='KEEP')
C
      WRITE (16,'(/A)') 'END OF PUMS'
      WRITE (*,'(/A)') 'END OF PUMS'
      
   99 CONTINUE
	RETURN
      
  198 WRITE (*,'(/A)') 'ERROR;  PROBLEM OPENING PUMS_HHTYPE_IN.TXT FILE'
	STOP 198

  199 WRITE (*,'(/A)') 'ERROR;  PROBLEM OPENING PUMS_HHTAB_IN.TXT FILE'
	STOP 199
      
  299 WRITE (*,'(/A)') 'ERROR;  HOUSEHOLD TYPE OUT OF RANGE ON PUMS_INPU
     AT.TXT FILE'
	STOP 299
  399 WRITE (*,'(/A)') 'ERROR;  MULTIPLE HOUSEHOLD TYPES IN PUMS_INPUT.T
     AXT'
	STOP 399
  499 WRITE (*,'(/A)') 'ERROR;  ROW COL INDEX GREATER THAN 4 IN PUMS_INP
     AUT.TXT'
	STOP 499    

	END	  				  		