      SUBROUTINE DATA3(ORIG,NOTRIP)
      IMPLICIT INTEGER (A-Z)
C*******************
C  THIS SUBROUTINE PROCESSES THE EMME DATABANK
C     IT IS CALLED ONCE FOR EACH ZONE SELECTED FOR ANALYSIS
C
C  THE EMMEBANK CONTAINS THE FOLLOWING FULL MATRICES
C  (DEFAULT MATRICES LISTED)
C       MF01 = TRANSIT FIRST MODES (FMD)
C       MF02 = TRANSIT LAST MODES (LMD)
C       MF03 = TRANSIT IN VEHICLE TIMES IN MINUTES (IVT)
C       MF04 = TRANSIT OUT OF VEHICLE TIMES IN MINUTES (OVT)
C       MF05 = TRANSIT HEADWAY OF FIRST MODE IN MINUTES (HWAY)
C       MF06 = TRANSIT PRIORITY MODE (PMD)
C       MF07 = TRANSIT FARES IN CENTS (FARE)
C       MF08 = HIGHWAY TRAVEL TIME SKIM TREES IN MINUTES (ZLHT)
C       MF09 = HIGHWAY TRAVEL DISTANCE SKIM TREES IN MILES (ZLHD)
C
C       MF21 = PERSON TRIPS (PTRIP)
C       MF22 = AUTO OCCUPANCY (COCC)
C*******************

	INCLUDE 'Common_params.fi'
	INCLUDE 'Common_emme4bank.fi'

	LOGICAL*4 NOTRIP

      REAL*4 TEST, RAN_NUM
C***********************************************************************
C
C     REOPEN EMMEBANK
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C      OPEN (UNIT=32, FILE='EMMEBANK',
C     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      OPEN (UNIT=901, FILE='emmemat/'//TEMX_FMD,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=902, FILE='emmemat/'//TEMX_LMD,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=903, FILE='emmemat/'//TEMX_IVT,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=904, FILE='emmemat/'//TEMX_OVT,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=905, FILE='emmemat/'//TEMX_HWAY,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=906, FILE='emmemat/'//TEMX_PMD,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=907, FILE='emmemat/'//TEMX_FARE,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')
      OPEN (UNIT=908, FILE='emmemat/'//TEMX_HTIME,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')      
      OPEN (UNIT=909, FILE='emmemat/'//TEMX_HDIST,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')      
      OPEN (UNIT=910, FILE='emmemat/'//TEMX_PTRIP,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')  
      
      IF (AOCC) OPEN (UNIT=911, FILE='emmemat/'//TEMX_AOCC,
     A  ACCESS='DIRECT',RECL=1,STATUS='OLD')  

C***********************************************************************
C
C     READ TABLES BY ROW
C
C***********************************************************************
      NOTRIP = .TRUE.

	P = ORIG

	DO Q=1,ZONES
C
C     P TO Q DIRECTION
C       
        REC1 = ((P-1)*mcent) + Q
        READ(901, REC=REC1) FMD(Q)
        READ(902, REC=REC1) LMD(Q)
        READ(903, REC=REC1) IVT(Q)
        READ(904, REC=REC1) OVT(Q)
        READ(905, REC=REC1) HWAY(Q)
        READ(906, REC=REC1) PMD(Q)
        READ(907, REC=REC1) FARE(Q)
        READ(908, REC=REC1) ZLHT(Q)
        READ(909, REC=REC1) ZLHD(Q)
        READ(910, REC=REC1) PTRIP(Q)
        
        PTRIP_IN = PTRIP_IN + PTRIP(Q)
C************ RWE CHANGE FOR I290 ROUND 3 MODELS MARCH 2013 ************
C
C       FOLLOWING COMMENTED OUT TO RETAIN FLOATING POINT TRIPS
C
C***********************************************************************
C	   TEST = PTRIP(Q) - INT(PTRIP(Q))
C
C  	   CALL RANDOM(RAN_NUM)
C        IF (RAN_NUM .GE. TEST) THEN
C 	     PTRIP(Q) = INT(PTRIP(Q))
C        ELSE 
C	     PTRIP(Q) = INT(PTRIP(Q)) + 1 
C	   ENDIF

	  IF (PTRIP(Q) .GT. 0.0) NOTRIP = .FALSE.  
	  
	  IF (AOCC) READ(911, REC=REC1) COCC(Q)

      ENDDO
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C     CHECK ADDED TO GET AROUND MISTAKE IN CMAP SKIMMING ROUTINE
C     IF IVT IS GREATER THAN 255 THEN PRIORITY MODE IS SET TO 2
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      DO Z=1,ZONES
	  IF (IVT(Z) .GT. 255) PMD(Z)=2
      ENDDO
C
C     FOLLOWING CODE TO TRACE ERRORS
C
      IF (TRACE) THEN

        WRITE(31,9001) ORIG

        DO Z=1,ZONES
          WRITE(31,9007)  Z,FMD(Z),LMD(Z),IVT(Z),OVT(Z),HWAY(Z),
     *      PMD(Z),FARE(Z),ZLHT(Z),ZLHD(Z),PTRIP(Z),COCC(Z)
        ENDDO
      ENDIF

 9001 FORMAT(/' FOR ORIGIN ZONE',I5,' THE EMME MATRIX DATA IS',/,
     A    ' ZONE   FMD   LMD    IVT    OVT   HWAY   PMD   FARE   ZLHT   
     BZLHD  PER TRIP  AUTO OCC')
 9007 FORMAT(' ',I4,2F6.0, 3F7.2, F6.0, 3F7.2, F10.1, F10.2)

      CLOSE (901)
      CLOSE (902)
      CLOSE (903)
      CLOSE (904)
      CLOSE (905)
      CLOSE (906)
      CLOSE (907)
      CLOSE (908)
      CLOSE (909)
      CLOSE (910)
      IF (AOCC) CLOSE(911)

      RETURN
      END