      SUBROUTINE DISGEN (PAR,RV)
C
C     DISTANCE GENERATOR
C
C     CHECKS DISTRIBUTION PARAMETER #3 (IN PAR(3)),CALLS APPROPRIATE
C     SUBROUTINE (PROCESS GENERATOR),AND RETURNS A VALUE FOR THE
C     RANDOM VARIABLE.
C
C## Revised for vectorized calculations - Heither, 11-02-2017
      IMPLICIT INTEGER*4 (A-Z)
      INCLUDE 'Common_params.fi'
      REAL*4  PAR(3)    
      REAL,DIMENSION (ITER) :: R1
	REAL,INTENT(OUT),DIMENSION (ITER) :: RV      
C
C     CHECK PAR(3)
C
C     PAR(3).LT.100 --- STRAIGHT LINE DISTRIBUTION
C     PAR(3).EQ.101 --- NORMAL DISTRIBUTION 
C     PAR(3).EQ.102 --- EXPONENTIAL DISTRIBUTION
C
C DEBUGGING:      WRITE (31,'(A,F8.2)') ' #### DISGEN Par(3)', PAR(3)
      IF(PAR(3)-101.) 01210,02040,02080

C     STRAIGHT LINE DISTRIBUTION

01210 CALL LINE (PAR,RV)
      RETURN
C 
C     NORMAL DISTRIBUTION
C
02040 CALL RNORM (PAR(1),PAR(2),RV)
C##  THE FOLLOWING LINE USED TO BE IN ADIST SUBROUTINE
	  WHERE(RV.LT.0.06) RV = 0.06
	  
      RETURN
C
C     EXPONENTIAL DISTRIBUTION
C
02080 CALL RANDOM_NUMBER(R1)
      WHERE(R1<0.0001) R1=0.0001
      WHERE(R1>0.9999) R1=0.9999 
      RV=-(1./PAR(1))*ALOG(1.-RAND1)

      RETURN
      END
