      PROGRAM CATS_PRE_DISTRIBUTION
C	USE DFLIB
      USE IFCORE
C***********************************************************************
C
C     THIS PROGRAM PREPARES THE HIGHWAY AND TRANSIT COSTS FOR THE 
C     CHICAGO AREA TRANSPORTATION STUDY'S TRIP DISTRIBUTION PROGRAM.
C     COSTS ARE HERE DEFINED AS THE TRANSIT AND HIGHWAY UTILITIES 
C     OBTAINED FROM THE CATS MODE CHOICE MODEL.  PROGRAM PREDIST 
C     CONTAINS MOST OF THE MODE CHOICE MODEL CODE.
C
C***********************************************************************
C
C     THIS VERSION OF THE PROGRAM WAS ASSEMBLED BY RONALD EASH FOR 
C     THE I-290 HIGH OCCUPANCY VEHICLE LANE STUDY.  THIS PROJECT WAS
C     CARRIED OUT AT THE CHICAGO OFFICE OF PB CONSULT AND WAS FUNDED
C     BY THE ILLINOIS DEPARTMENT OF TRANSPORTATION.
C
C***********************************************************************
C
C     THE PREPARATION OF THE CODE WAS STARTED JULY 28, 2001.
C     FIRST DRAFT COMPLETED           
C
C***********************************************************************
C
C     THIS VERSION OF THE PROGRAM WAS SLIGHTLY REVISED FOR THE PRAIRIE
C     PARKWAY PROJECT TO HANDLE 3000 ZONES.  THESE REVISIONS WERE
C     COMPLETED BY RWE IN MAY 2003.
C
C*********************************************************************** 
C
C     THE CODE REFLECTS THE ENHANCEMENTS IN TWO PREVIOUS VERSIONS
C     OF THE PROGRAM:
C
C     1.  THE PROGRAM UTILE1 THAT IS PART OF THE METRA MODELING PACKAGE
C         PREPARED BY PBQ AND D, SAN FRANCISCO OFFICE.
C     2.  SOURCE CODE DRAFTED BY DEAN ENGLUND OF CATS AND OBTAINED
C         BY EASH ON JULY 24, 2001.  
C
C***********************************************************************
C
C     PRINCIPAL FEATURES OF THIS VERSION OF THE PROGRAM ARE AS FOLLOWS:
C
C     1.  THE PROGRAM IS WRITTEN IN FORTRAN SOURCE CODE USING COMPAQ 
C         VISUAL FORTRAN, RELEASE 6.5A.  THE SOURCE CODE CAN BE COMPILED
C         AND RUN ON EITHER A PC WINDOWS (PB CONSULT) OR SUN UNIX (CATS)
C         PLATFORM.
C     2.  THE PROGRAM READS AND WRITES FILES DIRECTLY FROM AND INTO
C         EMME DATABANKS.
C     3.  OUTPUT IS DIRECTED TO A LENGTHY LOG FILE FOR REVIEW, ANALYSES,
C         AND DEBUGGING.  PROGRESS OF THE PROGRAM IS WRITTEN TO THE 
C         CONSOLE.
C     4.  INPUT FILES ARE SLIGHTLY REDESIGNED SO THAT CBD PARKING AND 
C         THE OPTIONAL DISTR PARAMETERS ARE READ IN SEPARATE FILES.
C     5.  MOST SECTIONS OF THE PROGRAM THAT ARE NO LONGER USED WERE
C         REMOVED.  THIS INCLUDES STATEMENTS THAT PACK AND UNPACK WORDS.  
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C     YET ANOTHER PASS THROUGH THE PROGRAM FOR THE REVISED I290 HOV 
C     STUDY STARTED IN JUNE 2009.
C
C     MOST CHANGES ARE NOTED IN BODY OF CODE.  NOTE THAT FILE NAMES
C     ARE NOW TAGGED WITH TRIP PURPOSE SINCE SEVERAL OF THE INPUT
C     FILES ARE NOW SPECIFIC TO TRIP PURPOSE.
C
C     INPUT EMMEBANK IS NOW NAMED EMMEBANK FOR CONSISTENCY WITH
C     EMME3.
C
C     APPROACH MODE DISTANCES ARE NOW DETERMINED FOR BUS AND 
C     FEEDER BUS IF M01 FILE INDICATES WAIT TIME NOT EQUAL TO 999.
C
C     MOST INPUT FILES HAVE BEEN REFORMATED AS COMMA DELIMITED FILES
C     FOR EASE OF PREPARATION.
C
C     PARK AND RIDE COSTS ARE INPUT FROM M01 FOR HOME-WORK AND NONWORK
C     PURPOSES.  NO ADJUSTMENT FOR PERIOD OF TIME PARKED SINCE IN
C     MANY CASES IT EFFECTIVELY COSTS MORE TO PARK AT STATION FOR
C     NONWORK TRIP THAT DOES NOT GET MONTHLY DISCOUNT.
C
C     GIVEN CURRENT COST STRUCTURE IT IS POSSIBLE TO HAVE NEGATIVE 
C     CBD PARKING COSTS.  RESET TO ZERO WHEN THIS OCCURS.
C
C     NOW POSSIBLE FOR ZONES TO HAVE THE SAME MINIMUM AND MAXIMUM 
C     ACCESS DISTANCE TO BUS.  THIS OCCURS WHEN ONLY A SMALL FRACTION
C     OF THE ZONE IS WITHIN REASONABLE WALKING DISTANCE OF A FEEDER/
C     REGULAR BUS LINE.  FOR THE PURPOSES OF THE MODEL ACCESS 
C     IS SET TO MINIMUM WHEN THIS OCCURS.
C
C     CODED INCOMES AND AUTO OCCUPANCIES UPDATED TO 2007-2009 LEVELS.
C
C     COMMENTS BY RWE 9/14/2009
C 
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C*******************  RWE CHANGE FOR I290 JUNE 2013  *******************
C
C     EMMEBANK READS AND WRITES CHANGED TO WORK WITH EXTERNAL MATRICES
C     PRODUCED BY EMME4 BY RWE JUNE 2013
C
C*******************  RWE CHANGE FOR I290 JUNE 2013  *******************
C############ Heither, 07-10-2018: updated to support 4000 zones
C############ Heither, 09-07-2018: provide Namelist file as argument to allow for simultaneous runs of PreDist by purpose     
C############ Heither, 01-12-2019: provide zonal interchange Random Seed file as argument 3 
      IMPLICIT INTEGER (A-Z)
C
C     COMMON AREAS
C
      INCLUDE 'Common_params.fi'
	INCLUDE 'Common_data.fi'
      INCLUDE 'Common_emme4bank.fi'
	INCLUDE 'Common_approach_model.fi'
	INCLUDE 'Common_cbdparking.fi'

	CHARACTER*1 ASTERIX(100)/100*'*'/
	CHARACTER*8 DATE8
      CHARACTER*10  CTIME10
      CHARACTER*2 DATE2(4), CTIME2(5)
      EQUIVALENCE (DATE8,DATE2(1)), (CTIME10,CTIME2(1))
	REAL*4 RAN_NUM
      LOGICAL*4 GOODORIG (4000)
      CHARACTER(LEN=30) :: FL1, FL2, FL3

C ### --- GET NAMELIST FILE ARGUMENT      
      CALL GETARG(1, FL1)
      CALL GETARG(2, FL2)
      CALL GETARG(3, FL3)
      FL1 = TRIM(ADJUSTL(FL1))
      FL2 = TRIM(ADJUSTL(FL2))
      FL3 = TRIM(ADJUSTL(FL3))

C***********************************************************************
C     FOLLOWING TRIP TYPES ASSUMED
C     TPTYPE = 1 HOME PRODUCTIONS TO WORK ATTRACTIONS
C     TPTYPE = 2 HOME PRODUCTIONS TO NON-WORK/NON-HOME ATTRACTIONS
C     TPTYPE = 3 NON-HOME PRODUCTIONS TO NON-HOME ATTRACTIONS
C***********************************************************************
C
C     OPEN OUTPUT LOG (UNIT=31)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************

      OPEN (UNIT=31,FILE=FL2,ERR=9931)
      OPEN (UNIT=40,FILE=FL3,ACCESS="DIRECT",RECL=1,ERR=9930)

C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (31,'(15A)') ' PRE-DISTRIBUTION LOGFILE OPENED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
C
C     LOGON
C     
      WRITE (*,'(100A1)') ASTERIX
      
      WRITE (*,'(/A)') ' CATS EMME4 PRE-DISTRIBUTION PROGRAM'
      WRITE (*,'(A)') ' REVISED BY RONALD EASH FOR UNIX AND PC FORTRAN'
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
	WRITE (*,'(A)') ' VERSION 1.4 (I290 HOV PROJECT WITH CURRENT COSTS
     A AND DETAILED CORRIDOR ZONES):  JUNE 2013'
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      WRITE (*,'(100A1)') ASTERIX
C
      WRITE (*,'(/A)') ' THE PROGRAM ESTIMATES THE ZONE TO ZONE HIGHWAY
     A TRANSIT AND'
      WRITE (*,'(A)') ' COMBINED HIGHWAY-TRANSIT UTILITIES FOR CATS INTE
     ARVENING'
      WRITE (*,'(A)') ' OPPORTUNITIES TRIP DISTRIBUTION MODEL USING THE 
     ASAME LOGIC'
      WRITE (*,'(A)') ' AND INPUTS AS THE CATS MODE CHOICE MODEL.  THIS 
     AMODE SPLIT'
      WRITE (*,'(A)') ' MODEL AND SOFTWARE WERE ORIGINALLY DEVELOPED BY 
     AYEHUDA GUR'
      WRITE (*,'(A)') ' IN THE EARLY 1970S AT THE CATS.'

      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' PROGRAM STARTED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
C
	WRITE (31,'(100A1)') ASTERIX
      WRITE (31,'(/A)') ' CATS EMME4 PRE-DISTRIBUTION PROGRAM'
      WRITE (31,'(A)') ' REVISED BY RONALD EASH FOR UNIX AND PC FORTRAN'
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
	WRITE (*,'(A)') ' VERSION 1.4 (I290 HOV PROJECT WITH CURRENT COSTS
     A AND DETAILED CORRIDOR ZONES):  JUNE 2013'
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      WRITE (31,'(100A1)') ASTERIX
C
      WRITE(31,'(/A)') ' THE PROGRAM ESTIMATES THE ZONE TO ZONE HIGHWAY
     A TRANSIT AND'
      WRITE(31,'(A)') ' COMBINED HIGHWAY-TRANSIT UTILITIES FOR CATS INTE
     ARVENING'
      WRITE(31,'(A)') ' OPPORTUNITIES TRIP DISTRIBUTION MODEL USING THE 
     ASAME LOGIC'
      WRITE(31,'(A)') ' AND INPUTS AS THE CATS MODE CHOICE MODEL.  THIS 
     AMODE SPLIT'
      WRITE(31,'(A)') ' MODEL AND SOFTWARE WERE ORIGINALLY DEVELOPED BY 
     AYEHUDA GUR'
      WRITE(31,'(A)') ' IN THE EARLY 1970S AT THE CATS.'
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (31,'(/15A)') ' PROGRAM STARTED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)

      WRITE (31,'(100A1)') ASTERIX      
C
C	OPEN PDLIST NAMELIST FILE (UNIT=33)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      OPEN (UNIT=33,FILE=FL1,ERR=9933)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
       CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' PD_NAMELIST.TXT OPENED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
       WRITE (31,'(/15A)') ' PD_NAMELIST.TXT OPENED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
       
C*******************
C  DATA1 SUBROUTINE READS THE NAMELIST PARAMETERS INPUT BY THE USER
C    DEFAULTS THOSE PARAMETERS NOT SPECIFIED
C    OBTAINS THE RANDOM NUMBER SEED
C*******************
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' PD_NAMELIST.TXT OPENED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
       WRITE (31,'(/15A)') ' PD_NAMELIST.TXT OPENED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
C
      CALL DATA1
C
      WRITE (*,'(/15A)') ' RETURN FROM DATA1:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      WRITE (31,'(/15A)') ' RETURN FROM DATA1:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      
      WRITE (31,'(100A1)') ASTERIX
      GOODORIG = ZOI
C
C	OPEN M01 FILE (UNIT=34)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (TPTYPE .EQ. 1) THEN
        OPEN (UNIT=34,FILE='PDHW_M01.TXT',ERR=9934)
      ELSE
	  IF (TPTYPE .EQ. 2) THEN
          OPEN (UNIT=34,FILE='PDHO_M01.TXT',ERR=9934)
        ELSE 
          OPEN (UNIT=34,FILE='PDNH_M01.TXT',ERR=9934)
        ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (TPTYPE .EQ. 1) THEN
        WRITE (*,'(/15A)')' PDHW_M01.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
        WRITE (31,'(/15A)')' PDHW_M01.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	ELSE
	  IF (TPTYPE .EQ. 2) THEN
          WRITE (*,'(/15A)')' PDHO_M01.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
          WRITE (31,'(/15A)')' PDHO_M01.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	  ELSE 
          WRITE (*,'(/15A)')' PDNH_M01.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
          WRITE (31,'(/15A)')' PDNH_M01.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	  ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C	OPEN M023 FILE (UNIT=35)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (TPTYPE .EQ. 1) THEN
        OPEN (UNIT=35,FILE='PDHW_M023.TXT',ERR=9935)
	ELSE
	  IF (TPTYPE .EQ. 2) THEN
          OPEN (UNIT=35,FILE='PDHO_M023.TXT',ERR=9935)
	  ELSE 
          OPEN (UNIT=35,FILE='PDNH_M023.TXT',ERR=9935)
	  ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (TPTYPE .EQ. 1) THEN
        WRITE (*,'(/15A)')' PDHW_M023.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
        WRITE (31,'(/15A)')' PDHW_M023.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	ELSE
	  IF (TPTYPE .EQ. 2) THEN
         WRITE (*,'(/15A)')' PDHO_M023.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
          WRITE (31,'(/15A)')' PDHO_M023 TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	  ELSE 
          WRITE (*,'(/15A)')' PDNH_M023.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
          WRITE (31,'(/15A)')' PDNH_M023.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	  ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C     DATA1 CALLED ABOVE
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C	OPEN CBD PARKING FILE, FILE THAT NOW CONTAINS THE CBD PARKING 
C     INPUTS SPECIFIED IN THE SUBMODEL DEVELOPED BY GORDON SCHULTZ
C     (UNIT=36)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF ((TPTYPE .EQ. 1) .AND. (NUMCBD_PARK .GT. 0)) THEN
        OPEN (UNIT=36,FILE='PDHW_CBDPARK.TXT',ERR=9936)
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (TPTYPE .EQ. 1) THEN
        WRITE (*,'(/15A)') ' PDHW_CBDPARK.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
        WRITE (31,'(/15A)')' PDHW_CBDPARK.TXT OPENED:  ',
     A    DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B    CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C	OPEN DISTR FILE, OPTIONAL FILE THAT NOW INCLUDES ONLY DISTR 
C     ARRAYS REQUIRED IF ASM_AREA OR ASM_ZONE IS TRUE (UNIT=37)
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (ASM_AREA .OR. ASM_ZONE) THEN
        IF (TPTYPE .EQ. 1) THEN
          OPEN (UNIT=37,FILE='PDHW_DISTR.TXT',ERR=9937)
	  ELSE
	    IF (TPTYPE .EQ. 2) THEN
            OPEN (UNIT=37,FILE='PDHO_DISTR.TXT',ERR=9937)
	    ELSE 
            OPEN (UNIT=37,FILE='PDNH_DISTR.TXT',ERR=9937)
	    ENDIF
        ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      IF (ASM_AREA .OR. ASM_ZONE) THEN
        IF (TPTYPE .EQ. 1) THEN
          WRITE (*,'(/15A)') ' PDHW_DISTR.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
          WRITE (31,'(/15A)') ' PDHW_DISTR.TXT OPENED:  ',
     A      DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B      CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	  ELSE
	    IF (TPTYPE .EQ. 2) THEN
            WRITE (*,'(/15A)') ' PDHO_DISTR.TXT OPENED:  ',
     A        DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B        CTIME2(1),':', CTIME2(2),':', CTIME2(3)
            WRITE (31,'(/15A)') ' PDHO_DISTR.TXT OPENED:  ',
     A        DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B        CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	    ELSE 
            WRITE (*,'(/15A)') ' PDNH_DISTR.TXT OPENED:  ',
     A        DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B        CTIME2(1),':', CTIME2(2),':', CTIME2(3)
            WRITE (31,'(/15A)') ' PDNH_DISTR.TXT OPENED:  ',
     A        DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B        CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	    ENDIF
        ENDIF
      ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C     SET RANDOM NUMBER SEED
C## HEITHER, 01-19-2019: THIS CODE IS OBSOLETE      
C
C##      IF (RNSEED .EQ. 0) THEN
C##        CALL SEED(RND$TIMESEED)
C        CALL RANDOM(RAN_NUM)
C##	  WRITE (*,'(/A,2I10)') ' RANDOM NUMBER SEEDS:  ', RND$TIMESEED
C	  WRITE (*,'(A,F11.8)') ' FIRST RANDOM NUMBER:  ', RAN_NUM
C##	  WRITE (31,'(/A,2I10)') ' RANDOM NUMBER SEEDS:  ', RND$TIMESEED
C        WRITE (31,'(A,F11.8)') ' FIRST RANDOM NUMBER:  ', RAN_NUM
C##	ELSE       
C##	  CALL SEED(RNSEED)
C	  CALL RANDOM(RAN_NUM) 
C##        WRITE (*,'(/A,2I10)') ' RANDOM NUMBER SEEDS:  ', RNSEED
C        WRITE (*,'(A,F11.8)') ' FIRST RANDOM NUMBER:  ', RAN_NUM
C##	  WRITE (31,'(/A,2I10)') ' RANDOM NUMBER SEEDS:  ', RNSEED
C        WRITE (31,'(A,F11.8)') ' FIRST RANDOM NUMBER:  ', RAN_NUM
C##	ENDIF

      WRITE (31,'(100A1)') ASTERIX
	  
C*******************
C  SUBROUTINE DATA2 READS ZONAL, ZONE TYPE & SYSTEM-WIDE PARAMETERS
C*******************
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' DATA2 CALLED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      WRITE (31,'(/15A)') ' DATA2 CALLED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
C
      CALL DATA2
C
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' RETURN FROM DATA2:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      WRITE (31,'(/15A)') ' RETURN FROM DATA2:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
C
C     OPEN UP THE EMMEBANK AND GET THE EMME PARAMETERS
C
      CALL OPEN_EMME4

	IF (mcent .LT. ZONES) THEN
	  WRITE (31,'(A, 2I5)') ' ERROR:  EMMEBANK DIMENSIONED SMALLER TH
     AAN MAXIMUM ZONE NUMBER', mcent, ZONES
	  STOP
	ENDIF   
	 
      CALL DATE_AND_TIME(DATE8,CTIME10)
	WRITE (*,'(/15A)') ' START MAIN LOOP FOR ORIGIN ZONES:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	WRITE (31,'(/15A)') ' START MAIN LOOP FOR ORIGIN ZONES:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      WRITE (31,'(100A1)') ASTERIX
C*******************
C  MAIN LOOP FOR ORIGINS
C*******************  
C      DO 10101 ORIG=1,MAXZONES
      DO ORIG=1,MAXZONES    
  
C##      WRITE (31,'(/A,11L1)') ' zoi 1-11:  ',zoi(1),zoi(2),zoi(3), 
C##     Azoi(4),zoi(5),zoi(6),zoi(7),zoi(8),zoi(9),zoi(10),zoi(11)   
C	IF (.NOT. ZOI(ORIG)) GO TO 10101
C      IF (ZOI(ORIG)) THEN
      IF (GOODORIG(ORIG)) THEN    
          CALL DATE_AND_TIME(DATE8,CTIME10)
C## Heither, 07-31-2017
C##      WRITE (31,'(/A,I4,15A)') ' BEGIN PROCESSING ZONE:  ',ORIG, 
C##     A ', ',CTIME2(1),':', CTIME2(2),':', CTIME2(3)

C##      WRITE (*,'(A,I4,15A)') ' BEGIN PROCESSING ZONE:  ',ORIG, 
C##     A ', ',CTIME2(1),':', CTIME2(2),':', CTIME2(3)

C*******************
C  SUBROUTINE DATA3 READS THE EMMEBANK MATRICES FOR THIS ORIGIN 
C*******************
          CALL DATA3(ORIG)
C*******************
C  SUBROUTINE TRIPS DOES THE SIMULATION OF CHOICES
C*******************
          CALL TRIPS(ORIG)
      ENDIF
C10101 CONTINUE
      ENDDO
C*******************
C  THE SIMULATION HAS BEEN COMPLETED FOR EACH ORIGIN SELECTED
C  FOR ANALYSIS.
C*******************
      GO TO 9999
C***********************************************************************
C
C     I/O ERRORS
C
C***********************************************************************  
 9930 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN RANDOM SEED FILE'
      STOP
      
 9931 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN LOGFILE OUTPUT FILE'
      STOP

 9933 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN PDLIST INPUT FILE'
      STOP

 9934 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN M01 INPUT FILE'
      STOP

 9935 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN M023 INPUT FILE'
      STOP

 9936 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN CBDPARK INPUT FILE'
      STOP

 9937 CONTINUE
      WRITE (*,*) 'ERROR:  UNABLE TO OPEN DISTR INPUT FILE'
      STOP

 9999 CONTINUE
      
      CALL DATE_AND_TIME(DATE8,CTIME10)
      WRITE (*,'(/15A)') ' PRE DISTRIBUTION PROGRAM COMPLETED:  ', 
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
      WRITE (*,'(100A1)') ASTERIX
      WRITE (31,'(/15A)') ' PRE DISTRIBUTION PROGRAM COMPLETED:  ',
     A DATE2(3),'/',DATE2(4),'/',DATE2(1), DATE2(2),'  ', 
     B CTIME2(1),':', CTIME2(2),':', CTIME2(3)
	WRITE (31,'(100A1)') ASTERIX
C
      CLOSE (31)
      CLOSE (32)
	CLOSE (33)
      CLOSE (34)
	CLOSE (35)
      CLOSE (40)

      STOP
      END