      SUBROUTINE INCDIS(ORIG,DEST,IMED,RINC)

	INCLUDE 'Common_params.fi'
      INCLUDE 'Common_data.fi'
      INTEGER *4 ORIG, DEST
      REAL,INTENT(OUT),DIMENSION (ITER) :: RINC

C*******************
C## Revised for vectorized calculations - Heither, 11-02-2017
C
C  THIS SUBROUTINE RETURNS A RANDOMLY ASSIGNED INCOME FOR THE TRIPMAKER
C       THE ZONAL MEDIAN INCOME IS INPUT (INTEGER)
C       AN INCOME IS OUTPUT (REAL)
C
C*******************
      R = IMED
C
C     MINIMUM MEDIAN HH INCOME IS $10000
C
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C     INCOME IS NOW IN DOLLARS RATHER THAN $100S
      R=AMAX1(R,10000.)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
      RMEAN = 1.58 * ALOG10(R) + 3.04
C
      SD = .42
C
C  THE CALL TO RNORM
C
      CALL RNORM(RMEAN,SD,RINC)
      RINC = EXP(RINC)
C
	IF (TRACE) THEN
	  WRITE (31, '(/A)') ' VALUES IN SUBROUTINE INCOME'
	  WRITE (31, '(A,I6)') '   ORIGIN ZONE=', ORIG
	  WRITE (31, '(A,I6)') '   DESTINATION ZONE=', DEST
  	  WRITE (31, '(A,F8.0)') '   MEDIAN HH INCOME (R)=',R  
        WRITE (31, '(A,F8.0)') '   SIMULATED HH INCOME (RINC)=',RINC(1)
	ENDIF
C
      RETURN
      END