# To use this file:
#   conda env create -f conda-environment.yml
name: CMAP-TRIP
channels:
  - tmip
  - conda-forge
  - defaults
dependencies:
  - altair=4.2
  - appdirs=1.4
  - cloudpickle=2.0
  - dask=2022.5
  - datashader=0.14
  - distributed=2022.5
  - tmip::emat=0.5
  - geopandas=0.10
  - gh=2.10
  - git=2.35
  - graphviz=3.0
  - ipykernel=6.13
  - ipyparallel=8.3
  - ipywidgets=7.7
  - joblib=1.1
  - jupyter=1.0
  - jupyter_contrib_nbextensions=0.5  # On conda-forge only
  - larch=5.5
  - matplotlib=3.5
  - nb_conda=2.2
  - notebook=6.4
  - numpy=1.22
  - pandas=1.3
  - pip=22.1
  - platypus-opt=1.0
  - plotly=5.8
  - pyarrow=8.0
  - pydot=1.4
  - pyscaffold=4.2
  - pytest=7.1
  - python=3.9
  - python-kaleido=0.2  # Plotly Static Image Export
  - pyzmq=22.3
  - salib=1.4
  - scikit-learn=1.1
  - scipy=1.8
  - seaborn=0.11
  - shortuuid=1.0
  - sqlalchemy=1.4
  - statsmodels=0.13
  - tbb=2021.5
  - tbb4py=2021.5
  - xarray=2022.3
  - zarr=2.11
  - pip:
    - -e .
    - -e ./sharrow