      SUBROUTINE SUB_CONTROL
      IMPLICIT INTEGER (A-Z)
C***********************************************************************
C
C     THE CONTROL SUBROUTINE READS NAMELISTS TO CONTROL THE OPERATION OF
C     THE TRIP GENERATION PROGRAM AND ESTABLISH REGIONAL HOUSEHOLD 
C     CONTROL TOTALS.
C
C***********************************************************************
C
C     &PARAM NAMELIST VARIABLES:
C
C          TITLE = TITLE DESCRIBING MODEL RUN (80 CHARACTERS MAX)
C       SUBZONES = NUMBER OF TRIP GENERATION SUBZONES
C       COUNTIES = NUMBER OF COUNTIES
C          PUMA5 = NUMBER OF FIVE PERCENT PUMS AREAS
C          PUMA1 = NUMBER OF ONE PERCENT PUMS AREAS 
C          ZONES = NUMBER OF ZONES FOR REMAINING MODELS
C        TRIPGEN = TRUE IF RUNNING TRIP GENERATION MODEL
C         HHENUM = TRUE IF RUNNING HOUSEHOLD ENUMERATION
C      SAVE_FILE = OPTION TO SAVE INTERMEDIATE HOUSEHOLD FILES (T/F) 
C                  DEFAULT IS FALSE
C      EXP_TTYPE = OPTION TO OUTPUT EXPANDED (49) TRIP TYPES THAT ARE
C                  USED WITHIN TRIP GENERATION CODE (T/F).  DEFAULT IS 
C                  FALSE
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
C    MODE_CHOICE = OPTION TO OUTPUT HOUSEHOLD FILE FOR MODE CHOICE 
C                  MODEL.  DEFAULT IS FALSE
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
C
C## Heither, 04-04-2018:
C    SYNTH_VEH = OPTION TO USE VEHICLES AVAILABLE FROM SYNTHETIC POPULATION (TRUE, DEFAULT)
C                  OR THE VEHICLE AVAILABLITY MODEL IN TRIP GENERATION CODE.
C     IN_EMPFACT = FACTOR FOR INDIANA EMPLOYMENT.  DEFAULT IS 1.00.
C     WI_EMPFACT = FACTOR FOR WISCONSIN EMPLOYMENT.   DEFAULT IS 1.00.
C
C***********************************************************************
C
C     &CONTROL NAMELIST VARIABLES:
C
C          HH_ADULTS = REGIONAL HOUSEHOLDS BY SIZE CATEGORIES 
C         HH_WORKERS = REGIONAL HOUSEHOLDS BY WORKER CATEGORIES
C        HH_CHILEREN = REGIONAL HOUSEHOLDS BY CHILDREN CATEGORIES
C     HH_HOUSEHOLDER = REGIONAL HOUSEHOLDS BY AGE OF HOUSEHOLDER 
C                      CATEGORIES
C             RNSEED = RANDOM NUMBER SEED (6843 IS DEFAULT)
C
C***********************************************************************
C
      INCLUDE 'COMMON_PARAM.FI'
      INCLUDE 'COMMON_CONTROL.FI'
C-- Heither, 03-13-2018: listed explicitly since not read from TG_Input      
      INTEGER,DIMENSION(4):: HH_ADULTS, HH_WORKERS, HH_CHILDREN, HH_INC4
      INTEGER,DIMENSION(3):: HH_HOUSEHOLDER
      INTEGER:: HH1_TOT, HH2_TOT, HH3_TOT, HH4_TOT, HH5_TOT
C
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
C    MODE_CHOICE = OPTION TO OUTPUT HOUSEHOLD FILE FOR MODE CHOICE 
C                  MODEL
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
	NAMELIST/PARAM/ TITLE, SUBZONES, COUNTIES, PUMA5, PUMA1, ZONES, 
     A  TRIPGEN, HHENUM, SAVE_FILE, EXP_TTYPE, MODE_CHOICE, SYNTH_VEH,
     B  IN_EMPFACT, WI_EMPFACT, RNSEED

C-- Heither, 03-14-2018:   RNSEED now under PARAM    
C--      NAMELIST/CONTROL/ HH_ADULTS, HH_WORKERS, HH_CHILDREN, 
C--     A  HH_HOUSEHOLDER, RNSEED
   
      
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
C    MODE_CHOICE = OPTION TO OUTPUT HOUSEHOLD FILE FOR MODE CHOICE 
C                  MODEL
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
C
C	INPUT NAMELIST IS UNIT 15
C
      OPEN (UNIT=15,FILE='TG_INPUT.TXT',STATUS='OLD',ERR=199)
C
C     READ PARAM NAMELIST
C
      SUBZONES = 0
	COUNTIES = 0
	PUMA5 = 0
	PUMA1 = 0
	ZONES = 0
      TRIPGEN = .TRUE.
      HHENUM = .FALSE.
	SAVE_FILE = .FALSE.
	EXP_TTYPE = .FALSE.
	SYNTH_VEH = .TRUE.
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
	MODE_CHOICE = .FALSE.
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
	IN_EMPFACT = 1.000
      WI_EMPFACT = 1.000
      RNSEED = 6843

      READ(15,PARAM,END=20)

      WRITE (*,'(/A)') 'TRIP GENERATION PARAMETERS'
	WRITE (*,'(A)')  '--------------------------'
      WRITE (*,'(A,A80)')'  TITLE = ', TITLE
	WRITE (*,'(A,I6)') '  SUBZONES =', SUBZONES
	WRITE (*,'(A,I6)') '  PUMA5 =', PUMA5
	WRITE (*,'(A,I6)') '  PUMA1 =', PUMA1
	WRITE (*,'(A,I6)') '  COUNTIES =', COUNTIES
	WRITE (*,'(A,I6)') '  ZONES =', ZONES
      WRITE (*,'(A,L4)') '  TRIPGEN =', TRIPGEN
      WRITE (*,'(A,L4)') '  HHENUM =', HHENUM
      WRITE (*,'(A,L4)') '  SAVE_FILE =', SAVE_FILE
      WRITE (*,'(A,L4)') '  EXP_TTYPE =', EXP_TTYPE
      WRITE (*,'(A,L4)') '  SYNTH_VEH =', SYNTH_VEH
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
      WRITE (*,'(A,L4)') '  MODE_CHOICE =', MODE_CHOICE
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
      WRITE (*,'(A,F6.3)') '  IN_EMPFACT = ', IN_EMPFACT
      WRITE (*,'(A,F6.3)') '  WI_EMPFACT = ', WI_EMPFACT
      WRITE (*,'(A,I6)')  '  RANDOM NUMBER SEED = ', RNSEED       

	WRITE (16,'(/A)') 'TRIP GENERATION PARAMETERS'
	WRITE (16,'(A)')  '--------------------------'
      WRITE (16,'(A,A80)')'  TITLE = ', TITLE
      WRITE (16,'(A,I6)') '  SUBZONES =', SUBZONES
      WRITE (16,'(A,I6)') '  PUMA5 =', PUMA5
      WRITE (16,'(A,I6)') '  PUMA1 =', PUMA1
	WRITE (16,'(A,I6)') '  COUNTIES =', COUNTIES
	WRITE (16,'(A,I6)') '  ZONES =', ZONES
      WRITE (16,'(A,L4)') '  TRIPGEN =', TRIPGEN
      WRITE (16,'(A,L4)') '  HHENUM =', HHENUM
      WRITE (16,'(A,L4)') '  SAVE_FILE =', SAVE_FILE
      WRITE (16,'(A,L4)') '  EXP_TTYPE =', EXP_TTYPE
      WRITE (16,'(A,L4)') '  SYNTH_VEH =', SYNTH_VEH
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
      WRITE (16,'(A,L4)') '  MODE_CHOICE =', MODE_CHOICE
C*******************  RWE CHANGE FOR I290 OCTOBER 2009  ****************
      WRITE (16,'(A,F6.3)') '  IN_EMPFACT = ', IN_EMPFACT
      WRITE (16,'(A,F6.3)') '  WI_EMPFACT = ', WI_EMPFACT
      WRITE (16,'(A,I6)')  '  RANDOM NUMBER SEED = ', RNSEED       
C
      IF (SUBZONES .LT. 1) GO TO 299
	IF (SUBZONES .GT. 25000) GO TO 399

	IF (PUMA5 .LT. 1) GO TO 699
	IF (PUMA5 .GT. 100) GO TO 799

	IF (PUMA1 .LT. 1) GO TO 1099
	IF (PUMA1 .GT. 30) GO TO 1199

	IF (COUNTIES .LT. 1) GO TO 899
	IF (COUNTIES .GT. 30) GO TO 999

	IF (ZONES .LT. 1) GO TO 1299
C## Heither 08-23-18: update for new zone system	
	IF (ZONES .GT. 4000) GO TO 1399
      
      IF (TRIPGEN .AND. HHENUM) GO TO 1599
      IF (.NOT. TRIPGEN .AND. NOT HHENUM) GO TO 1699
C
C     READ CONTROL NAMELIST
C   
      DO I=1,4
        HH_ADULTS(I)=0
        HH_WORKERS(I) = 0
        HH_CHILDREN(I) = 0
      ENDDO  
      
      DO I=1,3
        HH_HOUSEHOLDER = 0
      ENDDO
C-- Heither, 03-14-2018:   Code Block not needed        
C--      REWIND 15
C--      READ (15,CONTROL,END=20)
      GO TO 21
      
   20 WRITE (*,'(/A)') 'ERROR;  EARLY END OF FILE ON TG_INPUT.TXT'
      STOP 199
      
   21 CONTINUE
      
      HH1_TOT = HH_ADULTS(1)+HH_ADULTS(2)+HH_ADULTS(3)+HH_ADULTS(4)
      HH2_TOT = HH_WORKERS(1)+HH_WORKERS(2)+HH_WORKERS(3)+HH_WORKERS(4)
      HH3_TOT = HH_CHILDREN(1)+HH_CHILDREN(2)+HH_CHILDREN(3)+
     A  HH_CHILDREN(4)
      HH4_TOT = HH_HOUSEHOLDER(1)+HH_HOUSEHOLDER(2)+HH_HOUSEHOLDER(3)
            
      IF (HH1_TOT .NE. HH2_TOT) GO TO 1499
      IF (HH1_TOT .NE. HH3_TOT) GO TO 1499
      IF (HH1_TOT .NE. HH4_TOT) GO TO 1499
      
      HH_INC4(1) = HH1_TOT/4
      HH_INC4(2) = HH_INC4(1)
      HH_INC4(3) = HH_INC4(1)
      HH_INC4(4) = HH_INC4(1)
      
      HH5_TOT = 4 * HH_INC4(1)
      
      IF ((HH1_TOT-HH5_TOT) .EQ. 1) THEN
        HH_INC4(1) = HH_INC4(1) +1
      ENDIF
C
      IF ((HH1_TOT-HH5_TOT) .EQ. 2) THEN
        HH_INC4(1) = HH_INC4(1) +1
        HH_INC4(2) = HH_INC4(2) +1
      ENDIF
C
      IF ((HH1_TOT-HH5_TOT) .EQ. 3) THEN
        HH_INC4(1) = HH_INC4(1) +1
        HH_INC4(2) = HH_INC4(2) +1
        HH_INC4(3) = HH_INC4(3) +1
      ENDIF 
     
C
C-- Heither, 03-13-2018: Not using HH Control totals
C--	WRITE (*,'(/A)') 'REGIONAL HOUSEHOLD CONTROL TOTALS'
C--	WRITE (*,'(/A)') 'REGIONAL CONTROLS'	
C--	WRITE (*,'(A)')  '---------------------------------'
C--       WRITE (*,'(A,I8)')'  TOTAL HOUSEHOLDS = ', HH1_TOT
C--       WRITE (*,'(A,4I8)') '  HHS BY ADULTS (1,2,3,4+) =',
C--      A  HH_ADULTS
C--       WRITE (*,'(A,4I8)') '  HHS BY WORKERS (0,1,2,3+) =', HH_WORKERS
C--       WRITE (*,'(A,4I8)') '  HHS BY 0 TO 15 YR CHILDREN (0,1,2,3+) =',
C--      A  HH_CHILDREN
C-- 	WRITE (*,'(A,4I8)') '  HHS BY INCOME QUARTILE =',HH_INC4
C-- 	WRITE (*,'(A,3I8)') '  HHS BY HOUSEHOLDER AGE (LESS THAN 35,35-64,65+) 
C--      A=', HH_HOUSEHOLDER
C--      WRITE (*,'(A,I6)')  '  RANDOM NUMBER SEED = ', RNSEED 
C      
C--	WRITE (16,'(/A)') 'REGIONAL HOUSEHOLD CONTROL TOTALS'
C--	WRITE (16,'(/A)') 'REGIONAL CONTROLS'	
C--	WRITE (16,'(A)')  '---------------------------------'
C--      WRITE (16,'(A,I8)')'  TOTAL HOUSEHOLDS = ', HH1_TOT
C--      WRITE (16,'(A,4I8)') '  HHS BY ADULTS (1,2,3,4+) =',
C--     A  HH_ADULTS
C--      WRITE (16,'(A,4I8)') '  HHS BY WORKERS (0,1,2,3+) =', HH_WORKERS
C--      WRITE (16,'(A,4I8)') '  HHS BY 0 TO 15 YR CHILDREN (0,1,2,3+) =',
C--     A  HH_CHILDREN
C--	WRITE (16,'(A,4I8)') '  HHS BY INCOME QUARTILE =',HH_INC4
C--	WRITE (16,'(A,3I8)') '  HHS BY HOUSEHOLDER AGE (LESS THAN 35,35-64,65+)
C--     A =', HH_HOUSEHOLDER
C--      WRITE (*,'(A,I6)')   '  RANDOM NUMBER SEED = ', RNSEED 

      CLOSE (15,DISP='KEEP')
C
      WRITE (16,'(/A)') 'END OF CONTROL'
      WRITE (*,'(/A)') 'END OF CONTROL'

	RETURN

  199 WRITE (*,'(/A)') 'ERROR;  UNABLE TO OPEN TG_INPUT.TXT'
      STOP 199
  299 WRITE (*,'(/A)') 'ERROR;  NEED TO SPECIFY NUMBER OF TG SUBZONES'
      STOP 299
  399 WRITE (*,'(/A)') 'ERROR;  NUMBER OF TG SUBZONES EXCEEDS ARRAYS'
      STOP 399
  699 WRITE (*,'(/A)') 'ERROR;  NEED TO SPECIFY NUMBER OF FIVE PERCENT P
     AUMAS'
      STOP 699
  799 WRITE (*,'(/A)') 'ERROR;  NUMBER OF FIVE PERCENT PUMAS EXCEEDS ARR
     AAYS'
      STOP 799
  899 WRITE (*,'(/A)') 'ERROR;  NEED TO SPECIFY NUMBER OF COUNTIES'
      STOP 899
  999 WRITE (*,'(/A)') 'ERROR;  NUMBER OF COUNTIES EXCEEDS ARRAYS'
      STOP 999
 1099 WRITE (*,'(/A)') 'ERROR;  NEED TO SPECIFY NUMBER OF ONE PERCENT PU
     AMAS'
      STOP 1099
 1199 WRITE (*,'(/A)') 'ERROR;  NUMBER OF ONE PERCENT PUMAS EXCEEDS ARRA
     AYS'
      STOP 1199
 1299 WRITE (*,'(/A)') 'ERROR;  NEED TO SPECIFY NUMBER OF ZONES'
      STOP 299
 1399 WRITE (*,'(/A)') 'ERROR;  NUMBER OF ZONES EXCEEDS ARRAYS'
      STOP 399
 1499 WRITE (*,'(/A)') 'ERROR;  HOUSEHOLD CONTROL TOTALS UNEQUAL'
      STOP 1499
 1599 WRITE (*,'(/A)') 'ERROR;  BOTH TRIPGEN AND HHENUM ARE TRUE'
      STOP 1599 
 1699 WRITE (*,'(/A)') 'ERROR;  BOTH TRIPGEN AND HHENUM ARE FALSE'
      STOP 1699   
C
      END