      SUBROUTINE LINE (PAR,RV)
C
C     STRAIGHT LINE DISTRIBUTION. PARAMETERS STORED IN THE ARRAY 'PAR'.
C         PAR(1)= MINIMUM VALUE OF THE RANDOM VARIABLE
C         PAR(2)= MAXIMUM VALUE OF THE RANDOM VARIABLE
C         PAR(3)= PROBABILITY RATIO PROB AT RV(MIN) DIVIDED BY
C                   PROB AT RV(MAX) 
C              PAR(3).LT.1.0  INCREASING PROBABILITY (POSITIVE SLOPE)
C              PAR(3).EQ.1.0  UNIFORM PROBABILITY
C              PAR(3).GT.1.0  DECREASING PROBABILITY (NEGATIVE SLOPE)
C                             (NOT ALLOWED)
C
C## Revised for vectorized calculations - Heither, 11-02-2017  
      INCLUDE 'Common_params.fi'
      REAL*4  PAR(3)
      REAL,DIMENSION (ITER) :: Y, ARG, ZP, X, RAN1
      REAL,INTENT(OUT),DIMENSION (ITER) :: RV
C
      R=PAR(3)

	IF (R .GT. 1.) THEN
	  WRITE (31, '(A,3F8.3)')  '  ERROR:  PAR(3) IN DISTR GREATER THEN
     A1', PAR
        STOP
	ENDIF   

      XMN=PAR(1)
      DX=AMAX1( PAR(2)-XMN ,1.E-05)
      IF(DX.EQ.1.E-05) THEN
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
C     THIS CHANGE SETS RV TO THE MINIMUM BUS STOP DISTANCE WHEN MIN AND
C     MAX BUS STOP DISTANCE ARE EQUAL
C 
        RV = XMN
        RETURN
      ENDIF
C
C     FOLLOWING ORIGINAL CODE COMMENTED OUT
C
C	  WRITE(31,01202) DX, PAR
C        STOP
C      ENDIF
C01202 FORMAT('  ERROR:  DIFFERENCE BETWEEN XMIN & XMAX LESS THAN '
C     *       ,E10.3, 'PAR=', 3F8.3)
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
      CALL RANDOM_NUMBER(RAN1) 
	WHERE(RAN1<0.0001) RAN1=0.0001
	WHERE(RAN1>0.9999) RAN1=0.9999  

C     UNIFORM PROBABILITY DENSITY FUNCTION
      IF (R.EQ.1.) THEN
        RV=RAN1*DX+XMN
        RETURN
      ENDIF
C
C     NONUNIFORM PROBABILITY DENSITY FUNCTION
C     PREPARE BASIC VARIABLES
C
C     SLOPE - SLOPE OF THE LINE
C     AREA  - AREA UNDER THE CURVE
C     Y     - AREA BETWEEN XMN AND RESULT
C
      SLOPE=(1.-R)/DX
      AREA =.5*(1+R)*DX
C
C     COMPUTE 'Y' IN THE EQUATION .5*SLOPE*X**2-X+Y=0
C
      Y=RAN1*AREA
C
C     'ARG' IS THE TERM TO BE SQRTED IN QUADRATIC SOLUTION
C
C      ARG=1.-2.*SLOPE*Y 
C
C     ABOVE LINE CORRECTED BY EASH 9/1/2001
C
      ARG = (R**2.0) + 2.*SLOPE*Y
C
      ZP=SQRT(ARG)

      X = (ZP-R)/SLOPE
      RV=X+XMN
C DEBUGGING:        WRITE (31, '(A,10F8.3)')  '  RV FROM LINE',RV(1),RV(2),RV(3),
C DEBUGGING:       ARV(4),RV(5),RV(6),RV(7),RV(8),RV(9),RV(10) 
C DEBUGGING:        WRITE (31, '(A,10F8.3)')  '  RAN1 FROM LINE',RAN1(1),RAN1(2),
C DEBUGGING:       ARAN1(3),RAN1(4),RAN1(5),RAN1(6),RAN1(7),RAN1(8),RAN1(9),RAN1(10)       
      RETURN

      END