      SUBROUTINE ADIST(ORIG,DEST,FM,LM)
C
C     COMPUTES APPROACH DISTANCE TO FIRST AND LAST MODES.
C     USES DISTANCE DISTRIBUTION PARAMETERS STORED IN THE ARRAY 'DISTR'
C     RETURNS (1)DISTANCE TO FIRST MODE AND (2)DISTANCE TO LAST MODE.
C
C## Revised for vectorized calculations - Heither, 11-02-2017

      IMPLICIT INTEGER*4 (A-Z)
	INCLUDE 'Common_approach_model.fi'
	INCLUDE 'Common_params.fi'
      INCLUDE 'Common_data.fi'

      REAL*4 PAR(3)  
      REAL,DIMENSION (ITER) :: TEMP

C     VALUES STORED IN DOND(APROACH MODE, ORIGIN (1) OR DESTINATION (2))
C         (1) ... DISTANCE TO BUS
C         (2) ... DISTANCE TO RAPID TRANSIT
C         (3) ... DISTANCE TO RAIL ROAD
C         (4) ... DISTANCE TO FEEDER BUS
C         (5) ... DISTANCE TO PARK AND RIDE STATION
C DEBUGGING:      WRITE (31,'(A)') ' CHECK POINT 2 REACHED  '
      DO I=1,2

C     I=1 OBTAIN DISTANCES FOR ORIGIN
C     I=2 OBTAIN DISTANCES FOR DESTINATION
          IF(I.EQ.1) THEN
              Z=ORIG
              M=FM
	    ELSE
	        Z=DEST
              M=LM
	    ENDIF

		DO J=1,5		
C
C     OBTAIN APPROACH DISTANCES TO FIVE MODES
			DOND(1:ITER,J,I)=255.
C
C     GET DISTRIBUTION PARAMETERS.  NOTE CHANGE IN MODE ORDER
			IF (J .EQ. 1) THEN
				PAR(1) = DISTR(Z,3,1)
				PAR(2) = DISTR(Z,3,2)
				PAR(3) = DISTR(Z,3,3)
C DEBUGGING:                  WRITE (31,'(A,F8.2)') ' #### Par(3), J=1', PAR(3)
			ENDIF
			IF (J .EQ. 2) THEN
				PAR(1) = DISTR(Z,2,1)
				PAR(2) = DISTR(Z,2,2)
				PAR(3) = DISTR(Z,2,3)			
			ENDIF
			IF (J .EQ. 3) THEN
				PAR(1) = DISTR(Z,1,1)
				PAR(2) = DISTR(Z,1,2)
				PAR(3) = DISTR(Z,1,3)			
			ENDIF
			IF (J .EQ. 4) THEN
				PAR(1) = DISTR(Z,4,1)
				PAR(2) = DISTR(Z,4,2)
				PAR(3) = DISTR(Z,4,3)			
			ENDIF
			IF (J .EQ. 5) THEN
				PAR(1) = DISTR(Z,5,1)
				PAR(2) = DISTR(Z,5,2)
				PAR(3) = DISTR(Z,5,3)
			ENDIF      
C
C     GET APPROACH DISTANCE DEPENDING UPON FIRST/LAST MODE
C     J=1  BUS MODE. DISTANCE ALWAYS OBTAINED
C     J=2  RAPID TRANSIT. DISTANCE OBTAINED ONLY IF FIRST/LAST MODE
C          IS RAPID TRANSIT
C     J=3  RAIL ROAD.DISTANCE OBTAINED ONLY IF FIRST/LAST MODE IS RR 
C     J=4  FEEDER BUS.DISTANCE OBTAINED ONLY IF FIRST/LAST MODE IS RR.
C     J=5  PARK AND RIDE STATION DISTANCE OBTAINED WHEN I=1.

C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C     ONLY CALL DISGEN IF BUS IS AVAILABLE
			IF (J .EQ. 1 .AND. PAR(3) .NE. 999) THEN
C DEBUGGING:                    WRITE (31, '(A,10F8.4)')  '  RAND1 FROM ADIST',
C DEBUGGING:       ARAND1(1),RAND1(2),RAND1(3),RAND1(4),RAND1(5),RAND1(6),RAND1(7),
C DEBUGGING:       BRAND1(8),RAND1(9),RAND1(10)  
			 	CALL DISGEN (PAR,TEMP)
				DOND(1:ITER,J,I)=TEMP
			ENDIF
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
			IF (J.EQ.2 .AND. M.EQ.7 .AND. PAR(3).NE.999) THEN
				CALL DISGEN (PAR,TEMP)
				DOND(1:ITER,J,I)=TEMP
			ENDIF  
C  
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
			IF (J.EQ.3 .AND. M.EQ.8 .AND. PAR(3).NE.999) THEN
				CALL DISGEN (PAR,TEMP)
				DOND(1:ITER,J,I)=TEMP
			ENDIF 
C
			IF (J.EQ.4 .AND. M.EQ.8 .AND. PAR(3).NE.999) THEN
				CALL DISGEN (PAR,TEMP)
				DOND(1:ITER,J,I)=TEMP
			ENDIF 
C   PARK AND RIDE DISTANCE ONLY COMPUTED FROM ORIGIN
			IF (J.EQ.5 .AND. I.EQ.1 .AND. PAR(3).NE.999) THEN
				CALL DISGEN (PAR,TEMP)
				DOND(1:ITER,J,I)=TEMP
			ENDIF 
C            
C*******************  RWE CHANGE FOR I290 AUGUST-SEPT 2009  ************
C
		ENDDO
C
	ENDDO
C
C     WRITE APPROACH DISTANCES IF TRACE IS TURNED ON
	IF (TRACE ) THEN
	  WRITE (31, '(/A)') ' DISTANCES TO APPROACH MODES IN SUBROUTINE ADIST'
	  WRITE (31, '(A,I6)') '   ORIGIN ZONE=', ORIG
  	  WRITE (31, '(A,F6.2)') '     BUS DISTANCE=',DOND(1,1,1)
  	  WRITE (31, '(A,F6.2)') '     CTA RAIL DISTANCE=',DOND(1,2,1)
  	  WRITE (31, '(A,F6.2)') '     METRA RAIL DISTANCE=',DOND(1,3,1)
  	  WRITE (31, '(A,F6.2)') '     FEEDER BUS DISTANCE=',DOND(1,4,1)
  	  WRITE (31, '(A,F6.2)') '     P&R STATION DISTANCE=',DOND(1,5,1)
	  WRITE (31, '(A,I6)') '   DESTINATION ZONE=', DEST
  	  WRITE (31, '(A,F6.2)') '     BUS DISTANCE=',DOND(1,1,2)
  	  WRITE (31, '(A,F6.2)') '     CTA RAIL DISTANCE=',DOND(1,2,2)
  	  WRITE (31, '(A,F6.2)') '     METRA RAIL DISTANCE=',DOND(1,3,2)
  	  WRITE (31, '(A,F6.2)') '     FEEDER BUS DISTANCE=',DOND(1,4,2)
  	  WRITE (31, '(A,F6.2)') '     P&R STATION DISTANCE=',DOND(1,5,2)
	ENDIF
C
      RETURN
      END